# Generated by Django 4.1.2 on 2023-12-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='description',
            field=models.TextField(blank=True, default='', max_length=600, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('sirket', 'sirket'), ('sirketcalisani', 'sirketcalisani'), ('moderator', 'moderator')], default='sirket', max_length=100),
        ),
    ]
