# Generated by Django 4.1.2 on 2023-12-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_background_image_customuser_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='sehir',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='ulke',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='zip_kod',
        ),
        migrations.AddField(
            model_name='customuser',
            name='gorevi',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Görevi'),
        ),
    ]
