# Generated by Django 4.1.2 on 2024-01-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_personel_dosyalari'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='background_image',
            field=models.FileField(blank=True, null=True, upload_to='background/', verbose_name='background'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='profile/', verbose_name='Profile'),
        ),
    ]
