# Generated by Django 4.1.2 on 2024-03-10 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_lockscreenstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='personel_izinleri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kasa_virman_izni', models.BooleanField(default=False, verbose_name='Kasa Virman Yapma İzni')),
                ('kasa_olusturma_izni', models.BooleanField(default=False, verbose_name='Kasa Oluştuma İzni')),
                ('Kasa_silme_izni', models.BooleanField(default=False, verbose_name='Cari Silme İzni')),
                ('cari_olusturma', models.BooleanField(default=False, verbose_name='Cari Oluşturma İzni')),
                ('cari_silme_izni', models.BooleanField(default=False, verbose_name='Cari Silme İzni')),
                ('gelir_etiketi_olusturma', models.BooleanField(default=False, verbose_name='Gelir Etiketi Oluştuma İzni')),
                ('gelir_etiketi_silme', models.BooleanField(default=False, verbose_name='Gelir Etiketi Silme İzni ')),
                ('gider_etiketi_olusturma', models.BooleanField(default=False, verbose_name='Gider Etiketi Oluştuma İzni')),
                ('gider_etiketi_silme', models.BooleanField(default=False, verbose_name='Gider Etiketi Silme İzni ')),
                ('gider_kategorisi_olusturma', models.BooleanField(default=False, verbose_name='Gider Kategorisi Oluştuma İzni')),
                ('gider_kategorisi_silme', models.BooleanField(default=False, verbose_name='Gider Kategorisi Silme İzni ')),
                ('gelir_kategorisi_olusturma', models.BooleanField(default=False, verbose_name='Gelir Kategorisi Oluştuma İzni')),
                ('gelir_kategorisi_silme', models.BooleanField(default=False, verbose_name='Gelir Kategorisi Silme İzni ')),
                ('urun_olusturma', models.BooleanField(default=False, verbose_name='Ürün Oluştuma İzni')),
                ('urun_silme', models.BooleanField(default=False, verbose_name='Ürün Silme İzni ')),
                ('gelir_faturasi_kesme_izni', models.BooleanField(default=False, verbose_name='Geli Faturası Kesme İzni ')),
                ('gelir_faturasi_silme_izni', models.BooleanField(default=False, verbose_name='Geli Faturası Silme İzni ')),
                ('gelir_faturasi_duzenleme_izni', models.BooleanField(default=False, verbose_name='Geli Faturası Düzenleme İzni ')),
                ('gider_faturasi_kesme_izni', models.BooleanField(default=False, verbose_name='Geli Faturası Kesme İzni ')),
                ('gider_faturasi_silme_izni', models.BooleanField(default=False, verbose_name='Geli Faturası Silme İzni ')),
                ('gider_faturasi_duzenleme_izni', models.BooleanField(default=False, verbose_name='Geli Faturası Düzenleme İzni ')),
                ('gider_faturasi_makbuz_kesme_izni', models.BooleanField(default=False, verbose_name='Geli Faturası Makbuz Kesme İzni ')),
                ('gider_faturasi_makbuz_silme_izni', models.BooleanField(default=False, verbose_name='Geli Faturası Makbuz Silme İzni ')),
                ('gider_faturasi_makbuz_duzenleme_izni', models.BooleanField(default=False, verbose_name='Geli Faturası Makbuz Düzenleme İzni ')),
                ('gelir_faturasi_makbuz_kesme_izni', models.BooleanField(default=False, verbose_name='Geli Faturası Makbuz Kesme İzni ')),
                ('gelir_faturasi_makbuz_silme_izni', models.BooleanField(default=False, verbose_name='Geli Faturası Makbuz Silme İzni ')),
                ('gelir_faturasi_makbuz_duzenleme_izni', models.BooleanField(default=False, verbose_name='Geli Faturası Makbuz Düzenleme İzni ')),
                ('proje_tipi_olusturma', models.BooleanField(default=False, verbose_name='Proje Tipi Oluştuma  İzni')),
                ('proje_tipi_silme', models.BooleanField(default=False, verbose_name='Proje Tipi Silme İzni ')),
                ('santiye_olusturma', models.BooleanField(default=False, verbose_name='Şantiye Oluşturma İzni')),
                ('santiye_silme', models.BooleanField(default=False, verbose_name='Şantiye Silme İzni ')),
                ('santiye_kategoriler_olusturma', models.BooleanField(default=False, verbose_name='Şantiye Kategorileri Oluşturma İzni')),
                ('santiye_kategoriler_silme', models.BooleanField(default=False, verbose_name='Şantiye Kategorileri Silme İzni ')),
                ('sozlesmeler_olusturma', models.BooleanField(default=False, verbose_name='Sözleşmeler Oluşturma İzni')),
                ('sozlesmeler_silme', models.BooleanField(default=False, verbose_name='Sözleşmeler Silme İzni ')),
                ('hakedisler_olusturma', models.BooleanField(default=False, verbose_name='Hakedişler Oluşturma İzni')),
                ('hakedisler_silme', models.BooleanField(default=False, verbose_name='Hakedişler Silme İzni ')),
                ('izinlerin_sahibi_kullanici', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı Bilgisi')),
            ],
        ),
    ]
