# Generated by Django 4.2.13 on 2024-08-02 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_historicalpersonel_izinleri_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='isim',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Görevi'),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='isim',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Görevi'),
        ),
        migrations.CreateModel(
            name='bagli_kullanicilar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izinler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.personel_izinleri', verbose_name='Kullanıcı Bilgisi')),
                ('kullanicilar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı Bilgisi')),
            ],
        ),
    ]
