# Generated by Django 4.2.13 on 2024-08-23 17:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_historicalfaturalardaki_gelir_gider_etiketi_ozel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='calisanlar_kategorisi_baglama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(max_length=200, verbose_name='Çalışan Kategori İsmi')),
                ('silinme_bilgisi', models.BooleanField(default=False)),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Historicalcalisanlar_kategorisi_baglama',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('kategori', models.CharField(max_length=200, verbose_name='Çalışan Kategori İsmi')),
                ('silinme_bilgisi', models.BooleanField(default=False)),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical calisanlar_kategorisi_baglama',
                'verbose_name_plural': 'historical calisanlar_kategorisi_baglamas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Historicalcalisanlar_kategorisi',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('kategori_isimi', models.CharField(max_length=200, verbose_name='Çalışan Kategori İsmi')),
                ('silinme_bilgisi', models.BooleanField(default=False)),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('kategori_kime_ait', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Çalışan Kime Ait')),
            ],
            options={
                'verbose_name': 'historical calisanlar_kategorisi',
                'verbose_name_plural': 'historical calisanlar_kategorisis',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Historicalcalisanlar',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('isim', models.CharField(blank=True, max_length=200, null=True, verbose_name='İsim')),
                ('soyisim', models.CharField(blank=True, max_length=200, null=True, verbose_name='Soyisim')),
                ('maas', models.FloatField(blank=True, default=0, null=True, verbose_name='Maaş')),
                ('puantaj', models.FloatField(blank=True, default=0, null=True, verbose_name='Puantaj')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Gelir Açıklaması')),
                ('ulkeye_gelis_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Ülkeye Geliş Tarihi')),
                ('İse_baslama_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='İşe Başlama Tarihi')),
                ('silinme_bilgisi', models.BooleanField(default=False)),
                ('durum', models.BooleanField(default=False)),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('calisan_kime_ait', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Çalışan Kime Ait')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical calisanlar',
                'verbose_name_plural': 'historical calisanlars',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='calisanlar_kategorisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori_isimi', models.CharField(max_length=200, verbose_name='Çalışan Kategori İsmi')),
                ('silinme_bilgisi', models.BooleanField(default=False)),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('kategori_kime_ait', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Çalışan Kime Ait')),
            ],
        ),
        migrations.CreateModel(
            name='calisanlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(blank=True, max_length=200, null=True, verbose_name='İsim')),
                ('soyisim', models.CharField(blank=True, max_length=200, null=True, verbose_name='Soyisim')),
                ('maas', models.FloatField(blank=True, default=0, null=True, verbose_name='Maaş')),
                ('puantaj', models.FloatField(blank=True, default=0, null=True, verbose_name='Puantaj')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Gelir Açıklaması')),
                ('ulkeye_gelis_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Ülkeye Geliş Tarihi')),
                ('İse_baslama_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='İşe Başlama Tarihi')),
                ('silinme_bilgisi', models.BooleanField(default=False)),
                ('durum', models.BooleanField(default=False)),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('calisan_kime_ait', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Çalışan Kime Ait')),
            ],
        ),
    ]
