# Generated by Django 4.2.13 on 2024-08-28 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_calisanlar_kategorisi_baglama_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalpersonel_izinleri',
            old_name='kasa_virman_izni',
            new_name='kasa_virman_gorme_izni',
        ),
        migrations.RenameField(
            model_name='personel_izinleri',
            old_name='kasa_virman_izni',
            new_name='kasa_virman_gorme_izni',
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='cari_gosterme_izni',
            field=models.BooleanField(default=False, verbose_name='Kasa Oluştuma İzni'),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='cari_guncelleme_izni',
            field=models.BooleanField(default=False, verbose_name='Cari Silme İzni'),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='dashboard_duzenleme',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Silme İzni '),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='dashboard_gorme',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Oluşturma İzni'),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='dashboard_olusturma',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Oluşturma İzni'),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='dashboard_silme',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Silme İzni '),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='dosya_yoneticisi_duzenleme',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Silme İzni '),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='dosya_yoneticisi_gorme',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Oluşturma İzni'),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='dosya_yoneticisi_olusturma',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Oluşturma İzni'),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='dosya_yoneticisi_silme',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Silme İzni '),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='gelir_etiketi_gorme',
            field=models.BooleanField(default=False, verbose_name='Gelir Etiketi Silme İzni '),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='gelir_etiketi_guncelleme',
            field=models.BooleanField(default=False, verbose_name='Gelir Etiketi Oluştuma İzni'),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='gelir_faturasi_gorme_izni',
            field=models.BooleanField(default=False, verbose_name='Geli Faturası Kesme İzni '),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='gelir_faturasi_makbuz_gorme_izni',
            field=models.BooleanField(default=False, verbose_name='Geli Faturası Makbuz Düzenleme İzni '),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='gelir_kategorisi_gorme',
            field=models.BooleanField(default=False, verbose_name='Gelir Kategorisi Oluştuma İzni'),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='gelir_kategorisi_guncelleme',
            field=models.BooleanField(default=False, verbose_name='Gelir Kategorisi Silme İzni '),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='gelir_ozeti_duzenleme',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Silme İzni '),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='gelir_ozeti_gorme',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Oluşturma İzni'),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='gelir_ozeti_olusturma',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Oluşturma İzni'),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='gelir_ozeti_silme',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Silme İzni '),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='gider_etiketi_gorme',
            field=models.BooleanField(default=False, verbose_name='Gider Etiketi Silme İzni '),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='gider_etiketi_guncelleme',
            field=models.BooleanField(default=False, verbose_name='Gider Etiketi Oluştuma İzni'),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='gider_faturasi_gorme_izni',
            field=models.BooleanField(default=False, verbose_name='Geli Faturası Silme İzni '),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='gider_faturasi_makbuz_gorme_izni',
            field=models.BooleanField(default=False, verbose_name='Geli Faturası Makbuz Silme İzni '),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='gider_kategorisi_gorme',
            field=models.BooleanField(default=False, verbose_name='Gider Kategorisi Silme İzni '),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='gider_kategorisi_guncelleme',
            field=models.BooleanField(default=False, verbose_name='Gider Kategorisi Oluştuma İzni'),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='gider_ozeti_duzenleme',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Silme İzni '),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='gider_ozeti_gorme',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Oluşturma İzni'),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='gider_ozeti_olusturma',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Oluşturma İzni'),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='gider_ozeti_silme',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Silme İzni '),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='hakedisler_duzenleme',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Silme İzni '),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='hakedisler_gorme',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Oluşturma İzni'),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='hesap_ekstra_duzenleme',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Silme İzni '),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='hesap_ekstra_gorme',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Oluşturma İzni'),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='hesap_ekstra_olusturma',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Oluşturma İzni'),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='hesap_ekstra_silme',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Silme İzni '),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='ilerleme_takibi_duzenleme',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Silme İzni '),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='ilerleme_takibi_gorme',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Oluşturma İzni'),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='ilerleme_takibi_olusturma',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Oluşturma İzni'),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='ilerleme_takibi_silme',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Silme İzni '),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='is_plani_duzenleme',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Silme İzni '),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='is_plani_gorme',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Oluşturma İzni'),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='is_plani_olusturma',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Oluşturma İzni'),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='is_plani_silme',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Silme İzni '),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='kasa_gosterme_izni',
            field=models.BooleanField(default=False, verbose_name='Kasa Oluştuma İzni'),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='kasa_guncelleme_izni',
            field=models.BooleanField(default=False, verbose_name='Kasa Oluştuma İzni'),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='kasa_virman_olusturma_izni',
            field=models.BooleanField(default=False, verbose_name='Kasa Virman Yapma İzni'),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='personeller_duzenleme',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Silme İzni '),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='personeller_gorme',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Oluşturma İzni'),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='personeller_olusturma',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Oluşturma İzni'),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='personeller_silme',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Silme İzni '),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='proje_tipi_duzenleme',
            field=models.BooleanField(default=False, verbose_name='Proje Tipi Silme İzni '),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='proje_tipi_gorme',
            field=models.BooleanField(default=False, verbose_name='Proje Tipi Oluştuma  İzni'),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='projeler_duzenleme',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Silme İzni '),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='projeler_gorme',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Oluşturma İzni'),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='projeler_olusturma',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Oluşturma İzni'),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='projeler_silme',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Silme İzni '),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='santiye_duzenleme',
            field=models.BooleanField(default=False, verbose_name='Şantiye Silme İzni '),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='santiye_gorme',
            field=models.BooleanField(default=False, verbose_name='Şantiye Oluşturma İzni'),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='santiye_kategoriler_duzenleme',
            field=models.BooleanField(default=False, verbose_name='Şantiye Kategorileri Silme İzni '),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='santiye_kategoriler_gorme',
            field=models.BooleanField(default=False, verbose_name='Şantiye Kategorileri Oluşturma İzni'),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='sozlesmeler_duzenleme',
            field=models.BooleanField(default=False, verbose_name='Sözleşmeler Silme İzni '),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='sozlesmeler_gorme',
            field=models.BooleanField(default=False, verbose_name='Sözleşmeler Oluşturma İzni'),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='taseronlar_duzenleme',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Silme İzni '),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='taseronlar_gorme',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Oluşturma İzni'),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='taseronlar_olusturma',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Oluşturma İzni'),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='taseronlar_silme',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Silme İzni '),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='urun_gorme',
            field=models.BooleanField(default=False, verbose_name='Ürün Silme İzni '),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='urun_guncelleme',
            field=models.BooleanField(default=False, verbose_name='Ürün Oluştuma İzni'),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='virman_raporu_duzenleme',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Silme İzni '),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='virman_raporu_gorme',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Oluşturma İzni'),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='virman_raporu_olusturma',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Oluşturma İzni'),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='virman_raporu_silme',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Silme İzni '),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='yapilacaklar_duzenleme',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Silme İzni '),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='yapilacaklar_gorme',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Oluşturma İzni'),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='yapilacaklar_olusturma',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Oluşturma İzni'),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='yapilacaklar_silme',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Silme İzni '),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='cari_gosterme_izni',
            field=models.BooleanField(default=False, verbose_name='Kasa Oluştuma İzni'),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='cari_guncelleme_izni',
            field=models.BooleanField(default=False, verbose_name='Cari Silme İzni'),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='dashboard_duzenleme',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Silme İzni '),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='dashboard_gorme',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Oluşturma İzni'),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='dashboard_olusturma',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Oluşturma İzni'),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='dashboard_silme',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Silme İzni '),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='dosya_yoneticisi_duzenleme',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Silme İzni '),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='dosya_yoneticisi_gorme',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Oluşturma İzni'),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='dosya_yoneticisi_olusturma',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Oluşturma İzni'),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='dosya_yoneticisi_silme',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Silme İzni '),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='gelir_etiketi_gorme',
            field=models.BooleanField(default=False, verbose_name='Gelir Etiketi Silme İzni '),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='gelir_etiketi_guncelleme',
            field=models.BooleanField(default=False, verbose_name='Gelir Etiketi Oluştuma İzni'),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='gelir_faturasi_gorme_izni',
            field=models.BooleanField(default=False, verbose_name='Geli Faturası Kesme İzni '),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='gelir_faturasi_makbuz_gorme_izni',
            field=models.BooleanField(default=False, verbose_name='Geli Faturası Makbuz Düzenleme İzni '),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='gelir_kategorisi_gorme',
            field=models.BooleanField(default=False, verbose_name='Gelir Kategorisi Oluştuma İzni'),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='gelir_kategorisi_guncelleme',
            field=models.BooleanField(default=False, verbose_name='Gelir Kategorisi Silme İzni '),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='gelir_ozeti_duzenleme',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Silme İzni '),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='gelir_ozeti_gorme',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Oluşturma İzni'),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='gelir_ozeti_olusturma',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Oluşturma İzni'),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='gelir_ozeti_silme',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Silme İzni '),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='gider_etiketi_gorme',
            field=models.BooleanField(default=False, verbose_name='Gider Etiketi Silme İzni '),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='gider_etiketi_guncelleme',
            field=models.BooleanField(default=False, verbose_name='Gider Etiketi Oluştuma İzni'),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='gider_faturasi_gorme_izni',
            field=models.BooleanField(default=False, verbose_name='Geli Faturası Silme İzni '),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='gider_faturasi_makbuz_gorme_izni',
            field=models.BooleanField(default=False, verbose_name='Geli Faturası Makbuz Silme İzni '),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='gider_kategorisi_gorme',
            field=models.BooleanField(default=False, verbose_name='Gider Kategorisi Silme İzni '),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='gider_kategorisi_guncelleme',
            field=models.BooleanField(default=False, verbose_name='Gider Kategorisi Oluştuma İzni'),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='gider_ozeti_duzenleme',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Silme İzni '),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='gider_ozeti_gorme',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Oluşturma İzni'),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='gider_ozeti_olusturma',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Oluşturma İzni'),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='gider_ozeti_silme',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Silme İzni '),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='hakedisler_duzenleme',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Silme İzni '),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='hakedisler_gorme',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Oluşturma İzni'),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='hesap_ekstra_duzenleme',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Silme İzni '),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='hesap_ekstra_gorme',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Oluşturma İzni'),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='hesap_ekstra_olusturma',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Oluşturma İzni'),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='hesap_ekstra_silme',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Silme İzni '),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='ilerleme_takibi_duzenleme',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Silme İzni '),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='ilerleme_takibi_gorme',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Oluşturma İzni'),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='ilerleme_takibi_olusturma',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Oluşturma İzni'),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='ilerleme_takibi_silme',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Silme İzni '),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='is_plani_duzenleme',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Silme İzni '),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='is_plani_gorme',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Oluşturma İzni'),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='is_plani_olusturma',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Oluşturma İzni'),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='is_plani_silme',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Silme İzni '),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='kasa_gosterme_izni',
            field=models.BooleanField(default=False, verbose_name='Kasa Oluştuma İzni'),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='kasa_guncelleme_izni',
            field=models.BooleanField(default=False, verbose_name='Kasa Oluştuma İzni'),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='kasa_virman_olusturma_izni',
            field=models.BooleanField(default=False, verbose_name='Kasa Virman Yapma İzni'),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='personeller_duzenleme',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Silme İzni '),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='personeller_gorme',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Oluşturma İzni'),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='personeller_olusturma',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Oluşturma İzni'),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='personeller_silme',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Silme İzni '),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='proje_tipi_duzenleme',
            field=models.BooleanField(default=False, verbose_name='Proje Tipi Silme İzni '),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='proje_tipi_gorme',
            field=models.BooleanField(default=False, verbose_name='Proje Tipi Oluştuma  İzni'),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='projeler_duzenleme',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Silme İzni '),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='projeler_gorme',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Oluşturma İzni'),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='projeler_olusturma',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Oluşturma İzni'),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='projeler_silme',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Silme İzni '),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='santiye_duzenleme',
            field=models.BooleanField(default=False, verbose_name='Şantiye Silme İzni '),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='santiye_gorme',
            field=models.BooleanField(default=False, verbose_name='Şantiye Oluşturma İzni'),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='santiye_kategoriler_duzenleme',
            field=models.BooleanField(default=False, verbose_name='Şantiye Kategorileri Silme İzni '),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='santiye_kategoriler_gorme',
            field=models.BooleanField(default=False, verbose_name='Şantiye Kategorileri Oluşturma İzni'),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='sozlesmeler_duzenleme',
            field=models.BooleanField(default=False, verbose_name='Sözleşmeler Silme İzni '),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='sozlesmeler_gorme',
            field=models.BooleanField(default=False, verbose_name='Sözleşmeler Oluşturma İzni'),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='taseronlar_duzenleme',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Silme İzni '),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='taseronlar_gorme',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Oluşturma İzni'),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='taseronlar_olusturma',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Oluşturma İzni'),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='taseronlar_silme',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Silme İzni '),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='urun_gorme',
            field=models.BooleanField(default=False, verbose_name='Ürün Silme İzni '),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='urun_guncelleme',
            field=models.BooleanField(default=False, verbose_name='Ürün Oluştuma İzni'),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='virman_raporu_duzenleme',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Silme İzni '),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='virman_raporu_gorme',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Oluşturma İzni'),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='virman_raporu_olusturma',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Oluşturma İzni'),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='virman_raporu_silme',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Silme İzni '),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='yapilacaklar_duzenleme',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Silme İzni '),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='yapilacaklar_gorme',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Oluşturma İzni'),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='yapilacaklar_olusturma',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Oluşturma İzni'),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='yapilacaklar_silme',
            field=models.BooleanField(default=False, verbose_name='Hakedişler Silme İzni '),
        ),
    ]
