# Generated by Django 4.2.13 on 2024-08-29 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_rename_kasa_virman_izni_historicalpersonel_izinleri_kasa_virman_gorme_izni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bagli_kullanicilar',
            name='izinler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.personel_izinleri', verbose_name='Kullanıcı Bilgisi'),
        ),
        migrations.AlterField(
            model_name='bagli_kullanicilar',
            name='kullanicilar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı Bilgisi'),
        ),
    ]
