# Generated by Django 4.2.13 on 2024-08-30 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_historicalpersonel_izinleri_cari_detay_izni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='muhasabe_ayarlari_gorme',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='muhasabe_ayarlari_guncelleme',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='muhasabe_ayarlari_gorme',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='muhasabe_ayarlari_guncelleme',
            field=models.BooleanField(default=False),
        ),
    ]
