# Generated by Django 4.2.13 on 2024-09-01 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_historicalpersonel_izinleri_muhasabe_ayarlari_gorme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='ust_yuklenici_duzenleme',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='ust_yuklenici_gorme',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='ust_yuklenici_olusturma',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='ust_yuklenici_silme',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='ust_yuklenici_duzenleme',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='ust_yuklenici_gorme',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='ust_yuklenici_olusturma',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='ust_yuklenici_silme',
            field=models.BooleanField(default=False),
        ),
    ]
