# Generated by Django 4.2.13 on 2024-09-05 22:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_historicalpersonel_izinleri_ust_yuklenici_duzenleme_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='calisanlar_calismalari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normal_calisma_saati', models.FloatField(blank=True, default=0, null=True, verbose_name='Normal Çalışma Saati')),
                ('mesai_calisma_saati', models.FloatField(blank=True, default=0, null=True, verbose_name='Mesai Çalışma Saati')),
                ('tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Çalışma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date modified')),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Historicalcalisanlar_calismalari',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('normal_calisma_saati', models.FloatField(blank=True, default=0, null=True, verbose_name='Normal Çalışma Saati')),
                ('mesai_calisma_saati', models.FloatField(blank=True, default=0, null=True, verbose_name='Mesai Çalışma Saati')),
                ('tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Çalışma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date modified')),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical calisanlar_calismalari',
                'verbose_name_plural': 'historical calisanlar_calismalaris',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.DeleteModel(
            name='calisanlar_kategorisi_baglama',
        ),
        migrations.AddField(
            model_name='calisanlar',
            name='calisan_kategori',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.calisanlar_kategorisi', verbose_name='Çalışan Kategorisi'),
        ),
        migrations.AddField(
            model_name='historicalcalisanlar',
            name='calisan_kategori',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.calisanlar_kategorisi', verbose_name='Çalışan Kategorisi'),
        ),
        migrations.DeleteModel(
            name='Historicalcalisanlar_kategorisi_baglama',
        ),
        migrations.AddField(
            model_name='historicalcalisanlar_calismalari',
            name='calisan',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.calisanlar', verbose_name='işlem Kime Ait'),
        ),
        migrations.AddField(
            model_name='historicalcalisanlar_calismalari',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calisanlar_calismalari',
            name='calisan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.calisanlar', verbose_name='işlem Kime Ait'),
        ),
    ]
