# Generated by Django 4.2.13 on 2024-09-06 02:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_historicalcalisanlar_pozisyonu_calisanlar_pozisyonu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='calisan_maas_durumlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maas', models.FloatField(blank=True, default=0, null=True, verbose_name='Maaş')),
                ('puantaj', models.FloatField(blank=True, default=0, null=True, verbose_name='Puantaj')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Gelir Açıklaması')),
                ('durum', models.BooleanField(default=False)),
                ('para_birimi', models.BooleanField(default=False)),
                ('silinme_bilgisi', models.BooleanField(default=False)),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Historicalcalisan_maas_durumlari',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('maas', models.FloatField(blank=True, default=0, null=True, verbose_name='Maaş')),
                ('puantaj', models.FloatField(blank=True, default=0, null=True, verbose_name='Puantaj')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Gelir Açıklaması')),
                ('durum', models.BooleanField(default=False)),
                ('para_birimi', models.BooleanField(default=False)),
                ('silinme_bilgisi', models.BooleanField(default=False)),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical calisan_maas_durumlari',
                'verbose_name_plural': 'historical calisan_maas_durumlaris',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RemoveField(
            model_name='historicalcalisanlar_calismalari',
            name='calisan',
        ),
        migrations.RemoveField(
            model_name='historicalcalisanlar_calismalari',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='calisanlar',
            name='aciklama',
        ),
        migrations.RemoveField(
            model_name='calisanlar',
            name='durum',
        ),
        migrations.RemoveField(
            model_name='calisanlar',
            name='maas',
        ),
        migrations.RemoveField(
            model_name='calisanlar',
            name='puantaj',
        ),
        migrations.RemoveField(
            model_name='calisanlar',
            name='ulkeye_gelis_tarihi',
        ),
        migrations.RemoveField(
            model_name='calisanlar',
            name='İse_baslama_tarihi',
        ),
        migrations.RemoveField(
            model_name='historicalcalisanlar',
            name='aciklama',
        ),
        migrations.RemoveField(
            model_name='historicalcalisanlar',
            name='durum',
        ),
        migrations.RemoveField(
            model_name='historicalcalisanlar',
            name='maas',
        ),
        migrations.RemoveField(
            model_name='historicalcalisanlar',
            name='puantaj',
        ),
        migrations.RemoveField(
            model_name='historicalcalisanlar',
            name='ulkeye_gelis_tarihi',
        ),
        migrations.RemoveField(
            model_name='historicalcalisanlar',
            name='İse_baslama_tarihi',
        ),
        migrations.AddField(
            model_name='calisanlar',
            name='dogum_tarihi',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Doğum Tarihi'),
        ),
        migrations.AddField(
            model_name='calisanlar',
            name='pasaport_numarasi',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Pasaport Numarası'),
        ),
        migrations.AddField(
            model_name='calisanlar',
            name='telefon_numarasi',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon Numarasi'),
        ),
        migrations.AddField(
            model_name='calisanlar',
            name='uyrugu',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='uyruğu'),
        ),
        migrations.AddField(
            model_name='historicalcalisanlar',
            name='dogum_tarihi',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Doğum Tarihi'),
        ),
        migrations.AddField(
            model_name='historicalcalisanlar',
            name='pasaport_numarasi',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Pasaport Numarası'),
        ),
        migrations.AddField(
            model_name='historicalcalisanlar',
            name='telefon_numarasi',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon Numarasi'),
        ),
        migrations.AddField(
            model_name='historicalcalisanlar',
            name='uyrugu',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='uyruğu'),
        ),
        migrations.DeleteModel(
            name='calisanlar_calismalari',
        ),
        migrations.DeleteModel(
            name='Historicalcalisanlar_calismalari',
        ),
        migrations.AddField(
            model_name='historicalcalisan_maas_durumlari',
            name='calisan',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.calisanlar', verbose_name='işlem Kime Ait'),
        ),
        migrations.AddField(
            model_name='historicalcalisan_maas_durumlari',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calisan_maas_durumlari',
            name='calisan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.calisanlar', verbose_name='işlem Kime Ait'),
        ),
    ]
