# Generated by Django 4.2.13 on 2024-09-06 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_calisan_maas_durumlari_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calisanlar',
            name='profile',
            field=models.FileField(blank=True, null=True, upload_to='calisanprofili/', verbose_name='Sayfaya Logo Light'),
        ),
        migrations.AddField(
            model_name='historicalcalisanlar',
            name='profile',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Sayfaya Logo Light'),
        ),
    ]
