# Generated by Django 4.2.13 on 2024-09-06 02:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_calisanlar_profile_historicalcalisanlar_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historicalcalisan_belgeleri',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('belge_turu', models.CharField(blank=True, max_length=200, null=True, verbose_name='Soyisim')),
                ('belge', models.TextField(blank=True, max_length=100, null=True, verbose_name='Sayfaya Logo Light')),
                ('silinme_bilgisi', models.BooleanField(default=False)),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('calisan', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.calisanlar', verbose_name='işlem Kime Ait')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical calisan_belgeleri',
                'verbose_name_plural': 'historical calisan_belgeleris',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='calisan_belgeleri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belge_turu', models.CharField(blank=True, max_length=200, null=True, verbose_name='Soyisim')),
                ('belge', models.FileField(blank=True, null=True, upload_to='belge/', verbose_name='Sayfaya Logo Light')),
                ('silinme_bilgisi', models.BooleanField(default=False)),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('calisan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.calisanlar', verbose_name='işlem Kime Ait')),
            ],
        ),
    ]
