# Generated by Django 4.2.13 on 2024-09-06 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_historicalcalisan_belgeleri_calisan_belgeleri'),
    ]

    operations = [
        migrations.AddField(
            model_name='calisanlar',
            name='status',
            field=models.CharField(choices=[('0', '0'), ('1', '1')], default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='historicalcalisanlar',
            name='status',
            field=models.CharField(choices=[('0', '0'), ('1', '1')], default='0', max_length=100),
        ),
    ]
