# Generated by Django 4.2.13 on 2024-09-06 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_calisanlar_status_historicalcalisanlar_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calisan_maas_durumlari',
            old_name='puantaj',
            new_name='yevmiye',
        ),
        migrations.RenameField(
            model_name='historicalcalisan_maas_durumlari',
            old_name='puantaj',
            new_name='yevmiye',
        ),
        migrations.RemoveField(
            model_name='calisan_maas_durumlari',
            name='aciklama',
        ),
        migrations.RemoveField(
            model_name='historicalcalisan_maas_durumlari',
            name='aciklama',
        ),
    ]
