# Generated by Django 4.2.13 on 2024-09-06 22:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_rename_puantaj_calisan_maas_durumlari_yevmiye_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historicalcalisanlar_calismalari',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('normal_calisma_saati', models.FloatField(blank=True, default=0, null=True, verbose_name='Normal Çalışma Saati')),
                ('mesai_calisma_saati', models.FloatField(blank=True, default=0, null=True, verbose_name='Mesai Çalışma Saati')),
                ('mesai_oran_tutma', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=100)),
                ('tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Çalışma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date modified')),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('maas', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.calisan_maas_durumlari', verbose_name='işlem Kime Ait')),
            ],
            options={
                'verbose_name': 'historical calisanlar_calismalari',
                'verbose_name_plural': 'historical calisanlar_calismalaris',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='calisanlar_calismalari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normal_calisma_saati', models.FloatField(blank=True, default=0, null=True, verbose_name='Normal Çalışma Saati')),
                ('mesai_calisma_saati', models.FloatField(blank=True, default=0, null=True, verbose_name='Mesai Çalışma Saati')),
                ('mesai_oran_tutma', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=100)),
                ('tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Çalışma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date modified')),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('maas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.calisan_maas_durumlari', verbose_name='işlem Kime Ait')),
            ],
        ),
    ]
