# Generated by Django 4.2.13 on 2024-09-14 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_historicalcalisanlar_calismalari_odemeleri_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcalisanlar_calismalari_odemeleri',
            name='calisan',
        ),
        migrations.RemoveField(
            model_name='historicalcalisanlar_calismalari_odemeleri',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='calisanlar_calismalari_odemeleri',
        ),
        migrations.DeleteModel(
            name='Historicalcalisanlar_calismalari_odemeleri',
        ),
    ]
