# Generated by Django 4.2.13 on 2024-09-19 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_group_message_remove_chatroom_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='chatgrup_resimleri/', verbose_name='Profile'),
        ),
    ]
