# Generated by Django 4.2.13 on 2024-10-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_historicalpersonel_izinleri_katman_duzenleme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='point',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcustomuser',
            name='point',
            field=models.TextField(blank=True, null=True),
        ),
    ]
