# Generated by Django 4.2.13 on 2024-10-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_customuser_point_historicalcustomuser_point'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='point',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='historicalcustomuser',
            old_name='point',
            new_name='lat',
        ),
        migrations.AddField(
            model_name='customuser',
            name='lon',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcustomuser',
            name='lon',
            field=models.TextField(blank=True, null=True),
        ),
    ]
