# Generated by Django 4.2.13 on 2024-10-16 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_rename_point_customuser_lat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='lon',
        ),
        migrations.RemoveField(
            model_name='historicalcustomuser',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='historicalcustomuser',
            name='lon',
        ),
    ]
