# Generated by Django 4.2.13 on 2024-11-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_remove_customuser_lat_remove_customuser_lon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calisan_maas_durumlari',
            name='fazla_mesai_orani',
            field=models.FloatField(blank=True, default=0.2, null=True, verbose_name='Fazla_mesai Orani'),
        ),
        migrations.AddField(
            model_name='historicalcalisan_maas_durumlari',
            name='fazla_mesai_orani',
            field=models.FloatField(blank=True, default=0.2, null=True, verbose_name='Fazla_mesai Orani'),
        ),
    ]
