# Generated by Django 4.2.13 on 2024-11-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_customuser_imza_sifresi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='genel_rapor_onaylama',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='genel_rapor_onaylama',
            field=models.BooleanField(default=False),
        ),
    ]
