# Generated by Django 4.2.13 on 2024-11-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_historicalpersonel_izinleri_genel_rapor_onaylama_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='genel_rapor_silme',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='genel_rapor_silme',
            field=models.BooleanField(default=False),
        ),
    ]
