# Generated by Django 4.2.13 on 2024-11-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_historicalpersonel_izinleri_genel_rapor_silme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='musteri_duzenleme',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='musteri_gorme',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='musteri_olusturma',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='musteri_silme',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='musteri_duzenleme',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='musteri_gorme',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='musteri_olusturma',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='musteri_silme',
            field=models.BooleanField(default=False),
        ),
    ]
