# Generated by Django 4.2.13 on 2024-12-30 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_historicalpersonel_izinleri_musteri_duzenleme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='kullanici_tercih_dili',
            field=models.CharField(default='en', max_length=10, verbose_name='Kullanıcı Tercih Dili'),
        ),
        migrations.AddField(
            model_name='historicalcustomuser',
            name='kullanici_tercih_dili',
            field=models.CharField(default='en', max_length=10, verbose_name='Kullanıcı Tercih Dili'),
        ),
    ]
