# Generated by Django 4.2.13 on 2025-01-01 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_customuser_kullanici_tercih_dili_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='crm_daire_duzenleme',
            field=models.BooleanField(default=False, verbose_name='CRM Daire Düzenleme İzni'),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='crm_daire_gorme',
            field=models.BooleanField(default=False, verbose_name='CRM Daire Görme İzni'),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='crm_daire_olusturma',
            field=models.BooleanField(default=False, verbose_name='CRM Daire Oluşturma İzni'),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='crm_daire_silme',
            field=models.BooleanField(default=False, verbose_name='CRM Daire Silme İzni'),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='crm_evrak_duzenleme',
            field=models.BooleanField(default=False, verbose_name='CRM Evrak Düzenleme İzni'),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='crm_evrak_gorme',
            field=models.BooleanField(default=False, verbose_name='CRM Evrak Görme İzni'),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='crm_evrak_olusturma',
            field=models.BooleanField(default=False, verbose_name='CRM Evrak Oluşturma İzni'),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='crm_evrak_silme',
            field=models.BooleanField(default=False, verbose_name='CRM Evrak Silme İzni'),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='crm_musteri_duzenleme',
            field=models.BooleanField(default=False, verbose_name='CRM Müşteri Düzenleme İzni'),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='crm_musteri_gorme',
            field=models.BooleanField(default=False, verbose_name='CRM Müşteri Görme İzni'),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='crm_musteri_olusturma',
            field=models.BooleanField(default=False, verbose_name='CRM Müşteri Oluşturma İzni'),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='crm_musteri_silme',
            field=models.BooleanField(default=False, verbose_name='CRM Müşteri Silme İzni'),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='crm_talep_duzenleme',
            field=models.BooleanField(default=False, verbose_name='CRM Talep Düzenleme İzni'),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='crm_talep_gorme',
            field=models.BooleanField(default=False, verbose_name='CRM Talep Görme İzni'),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='crm_talep_olusturma',
            field=models.BooleanField(default=False, verbose_name='CRM Talep Oluşturma İzni'),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='crm_talep_silme',
            field=models.BooleanField(default=False, verbose_name='CRM Talep Silme İzni'),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='crm_teklif_duzenleme',
            field=models.BooleanField(default=False, verbose_name='CRM Teklif Düzenleme İzni'),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='crm_teklif_gorme',
            field=models.BooleanField(default=False, verbose_name='CRM Teklif Görme İzni'),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='crm_teklif_olusturma',
            field=models.BooleanField(default=False, verbose_name='CRM Teklif Oluşturma İzni'),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='crm_teklif_silme',
            field=models.BooleanField(default=False, verbose_name='CRM Teklif Silme İzni'),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='crm_daire_duzenleme',
            field=models.BooleanField(default=False, verbose_name='CRM Daire Düzenleme İzni'),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='crm_daire_gorme',
            field=models.BooleanField(default=False, verbose_name='CRM Daire Görme İzni'),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='crm_daire_olusturma',
            field=models.BooleanField(default=False, verbose_name='CRM Daire Oluşturma İzni'),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='crm_daire_silme',
            field=models.BooleanField(default=False, verbose_name='CRM Daire Silme İzni'),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='crm_evrak_duzenleme',
            field=models.BooleanField(default=False, verbose_name='CRM Evrak Düzenleme İzni'),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='crm_evrak_gorme',
            field=models.BooleanField(default=False, verbose_name='CRM Evrak Görme İzni'),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='crm_evrak_olusturma',
            field=models.BooleanField(default=False, verbose_name='CRM Evrak Oluşturma İzni'),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='crm_evrak_silme',
            field=models.BooleanField(default=False, verbose_name='CRM Evrak Silme İzni'),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='crm_musteri_duzenleme',
            field=models.BooleanField(default=False, verbose_name='CRM Müşteri Düzenleme İzni'),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='crm_musteri_gorme',
            field=models.BooleanField(default=False, verbose_name='CRM Müşteri Görme İzni'),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='crm_musteri_olusturma',
            field=models.BooleanField(default=False, verbose_name='CRM Müşteri Oluşturma İzni'),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='crm_musteri_silme',
            field=models.BooleanField(default=False, verbose_name='CRM Müşteri Silme İzni'),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='crm_talep_duzenleme',
            field=models.BooleanField(default=False, verbose_name='CRM Talep Düzenleme İzni'),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='crm_talep_gorme',
            field=models.BooleanField(default=False, verbose_name='CRM Talep Görme İzni'),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='crm_talep_olusturma',
            field=models.BooleanField(default=False, verbose_name='CRM Talep Oluşturma İzni'),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='crm_talep_silme',
            field=models.BooleanField(default=False, verbose_name='CRM Talep Silme İzni'),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='crm_teklif_duzenleme',
            field=models.BooleanField(default=False, verbose_name='CRM Teklif Düzenleme İzni'),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='crm_teklif_gorme',
            field=models.BooleanField(default=False, verbose_name='CRM Teklif Görme İzni'),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='crm_teklif_olusturma',
            field=models.BooleanField(default=False, verbose_name='CRM Teklif Oluşturma İzni'),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='crm_teklif_silme',
            field=models.BooleanField(default=False, verbose_name='CRM Teklif Silme İzni'),
        ),
    ]
