# Generated by Django 4.2.13 on 2025-03-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0057_historicalpersonel_izinleri_santiye_kontrol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calisanlar',
            name='dogum_tarihi',
            field=models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi'),
        ),
        migrations.AlterField(
            model_name='historicalcalisanlar',
            name='dogum_tarihi',
            field=models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi'),
        ),
    ]
