# Generated by Django 4.2.13 on 2025-05-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0058_alter_calisanlar_dogum_tarihi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='rapor_olusturucu_gorme',
            field=models.BooleanField(default=False, verbose_name='Rapor Oluşturucu Görme İzni'),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='rapor_olusturucu_olusturma',
            field=models.BooleanField(default=False, verbose_name='Rapor Oluşturucu Oluşturma İzni'),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='rapor_olusturucu_gorme',
            field=models.BooleanField(default=False, verbose_name='Rapor Oluşturucu Görme İzni'),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='rapor_olusturucu_olusturma',
            field=models.BooleanField(default=False, verbose_name='Rapor Oluşturucu Oluşturma İzni'),
        ),
        migrations.AlterField(
            model_name='historicalpersonel_izinleri',
            name='dashboard_gorme',
            field=models.BooleanField(default=True, verbose_name='Hakedişler Oluşturma İzni'),
        ),
        migrations.AlterField(
            model_name='historicalpersonel_izinleri',
            name='dashboard_olusturma',
            field=models.BooleanField(default=True, verbose_name='Hakedişler Oluşturma İzni'),
        ),
        migrations.AlterField(
            model_name='personel_izinleri',
            name='dashboard_gorme',
            field=models.BooleanField(default=True, verbose_name='Hakedişler Oluşturma İzni'),
        ),
        migrations.AlterField(
            model_name='personel_izinleri',
            name='dashboard_olusturma',
            field=models.BooleanField(default=True, verbose_name='Hakedişler Oluşturma İzni'),
        ),
    ]
