# Generated by Django 4.2.13 on 2025-05-10 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0059_historicalpersonel_izinleri_rapor_olusturucu_gorme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='rfi_duzenleme',
            field=models.BooleanField(default=False, verbose_name='RFI Düzenleme İzni'),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='rfi_gorme',
            field=models.BooleanField(default=False, verbose_name='RFI Görme İzni'),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='rfi_listesi_duzenleme',
            field=models.BooleanField(default=False, verbose_name='RFI Listesi Düzenleme İzni'),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='rfi_listesi_gorme',
            field=models.BooleanField(default=False, verbose_name='RFI Listesi Görme İzni'),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='rfi_listesi_olusturma',
            field=models.BooleanField(default=False, verbose_name='RFI Listesi Oluşturma İzni'),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='rfi_listesi_onaylama_gorme',
            field=models.BooleanField(default=False, verbose_name='RFI Listesi Onaylama Görme İzni'),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='rfi_listesi_onaylama_olustur',
            field=models.BooleanField(default=False, verbose_name='RFI Listesi Onaylama İzni'),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='rfi_listesi_onaylama_silme',
            field=models.BooleanField(default=False, verbose_name='RFI Listesi Onaylama Silme İzni'),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='rfi_listesi_silme',
            field=models.BooleanField(default=False, verbose_name='RFI Listesi Silme İzni'),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='rfi_olusturma',
            field=models.BooleanField(default=False, verbose_name='RFI Oluşturma İzni'),
        ),
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='rfi_silme',
            field=models.BooleanField(default=False, verbose_name='RFI Silme İzni'),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='rfi_duzenleme',
            field=models.BooleanField(default=False, verbose_name='RFI Düzenleme İzni'),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='rfi_gorme',
            field=models.BooleanField(default=False, verbose_name='RFI Görme İzni'),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='rfi_listesi_duzenleme',
            field=models.BooleanField(default=False, verbose_name='RFI Listesi Düzenleme İzni'),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='rfi_listesi_gorme',
            field=models.BooleanField(default=False, verbose_name='RFI Listesi Görme İzni'),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='rfi_listesi_olusturma',
            field=models.BooleanField(default=False, verbose_name='RFI Listesi Oluşturma İzni'),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='rfi_listesi_onaylama_gorme',
            field=models.BooleanField(default=False, verbose_name='RFI Listesi Onaylama Görme İzni'),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='rfi_listesi_onaylama_olustur',
            field=models.BooleanField(default=False, verbose_name='RFI Listesi Onaylama İzni'),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='rfi_listesi_onaylama_silme',
            field=models.BooleanField(default=False, verbose_name='RFI Listesi Onaylama Silme İzni'),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='rfi_listesi_silme',
            field=models.BooleanField(default=False, verbose_name='RFI Listesi Silme İzni'),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='rfi_olusturma',
            field=models.BooleanField(default=False, verbose_name='RFI Oluşturma İzni'),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='rfi_silme',
            field=models.BooleanField(default=False, verbose_name='RFI Silme İzni'),
        ),
    ]
