# Generated by Django 4.2.13 on 2025-05-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0060_historicalpersonel_izinleri_rfi_duzenleme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpersonel_izinleri',
            name='gant_silme',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personel_izinleri',
            name='gant_silme',
            field=models.BooleanField(default=False),
        ),
    ]
