# Generated by Django 4.2.13 on 2025-05-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0061_historicalpersonel_izinleri_gant_silme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='platform',
            field=models.CharField(choices=[('web', 'Web'), ('android', 'Android'), ('ios', 'iOS')], default='web', max_length=10, verbose_name='Platform'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Token'),
        ),
        migrations.AddField(
            model_name='historicalcustomuser',
            name='platform',
            field=models.CharField(choices=[('web', 'Web'), ('android', 'Android'), ('ios', 'iOS')], default='web', max_length=10, verbose_name='Platform'),
        ),
        migrations.AddField(
            model_name='historicalcustomuser',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Token'),
        ),
    ]
