# Generated by Django 4.1.2 on 2023-12-16 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='proje_tipi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Proje_tipi_adi', models.CharField(blank=True, max_length=400, null=True, verbose_name='Proje Tipi Adı')),
                ('silinme_bilgisi', models.BooleanField(default=False)),
                ('proje_ait_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Proje Tipi Ait Olduğu')),
            ],
        ),
    ]
