# Generated by Django 4.1.2 on 2023-12-16 13:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('site_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proje_tipi',
            name='kayit_tarihi',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
        migrations.CreateModel(
            name='santiye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proje_adi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Proje Adı')),
                ('kat_sayisi', models.FloatField(default=1, verbose_name='Kat Bilgisi')),
                ('blog_sayisi', models.FloatField(default=1, verbose_name='Blog Bilgisi')),
                ('silinme_bilgisi', models.BooleanField(default=False)),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('proje_ait_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Proje Ait Olduğu')),
                ('proje_tipi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_info.proje_tipi', verbose_name='Proje Tipi Ait Olduğu')),
            ],
        ),
    ]
