# Generated by Django 4.1.2 on 2023-12-16 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('site_info', '0002_proje_tipi_kayit_tarihi_santiye'),
    ]

    operations = [
        migrations.AlterField(
            model_name='santiye',
            name='blog_sayisi',
            field=models.BigIntegerField(default=1, verbose_name='Blog Bilgisi'),
        ),
        migrations.CreateModel(
            name='bloglar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_adi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Blog Adı')),
                ('blog_numarasi', models.BigIntegerField(default=1, verbose_name='Blog Numarasi')),
                ('proje_ait_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Proje Ait Olduğu')),
                ('proje_santiye_Ait', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_info.santiye', verbose_name='santiye Ait Olduğu')),
            ],
        ),
    ]
