# Generated by Django 4.1.2 on 2023-12-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_info', '0003_alter_santiye_blog_sayisi_bloglar'),
    ]

    operations = [
        migrations.AddField(
            model_name='proje_tipi',
            name='durum_bilgisi',
            field=models.BooleanField(default=True),
        ),
    ]
