# Generated by Django 4.1.2 on 2023-12-18 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_info', '0004_proje_tipi_durum_bilgisi'),
    ]

    operations = [
        migrations.AddField(
            model_name='santiye',
            name='blog_adi',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Blog Adı'),
        ),
    ]
