# Generated by Django 4.1.2 on 2023-12-26 14:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('site_info', '0005_santiye_blog_adi'),
    ]

    operations = [
        migrations.CreateModel(
            name='santiye_kalemleri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kalem_adi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Kalem Adı')),
                ('santiye_agirligi', models.FloatField(default=0, verbose_name='Kalem Şantiye Ağırlığı')),
                ('santiye_finansal_agirligi', models.FloatField(default=0, verbose_name='Kalem Finansal Ağırlık')),
                ('silinme_bilgisi', models.BooleanField(default=False)),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('proje_ait_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Proje Ait Olduğu')),
                ('proje_santiye_Ait', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_info.santiye', verbose_name='santiye Ait Olduğu')),
            ],
        ),
    ]
