# Generated by Django 4.1.2 on 2023-12-26 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_info', '0007_santiye_kalemlerin_dagilisi'),
    ]

    operations = [
        migrations.AddField(
            model_name='santiye_kalemlerin_dagilisi',
            name='kalem_bilgisi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_info.santiye_kalemleri', verbose_name='Kalem Ait Olduğu'),
        ),
    ]
