# Generated by Django 4.1.2 on 2023-12-26 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('site_info', '0008_santiye_kalemlerin_dagilisi_kalem_bilgisi'),
    ]

    operations = [
        migrations.CreateModel(
            name='projeler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proje_Adi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Proje Adı')),
                ('tarih', models.DateField(blank=True, null=True, verbose_name='Proje Tarihi')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('durum', models.CharField(blank=True, max_length=200, null=True, verbose_name='Durum')),
                ('proje_ait_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Proje Ait Olduğu')),
            ],
        ),
    ]
