# Generated by Django 4.1.2 on 2023-12-26 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_info', '0009_projeler'),
    ]

    operations = [
        migrations.CreateModel(
            name='proje_dosyalari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosya', models.FileField(blank=True, null=True, upload_to='', verbose_name='Dosya Adı')),
                ('proje_ait_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_info.projeler', verbose_name='Proje Ait Olduğu')),
            ],
        ),
    ]
