# Generated by Django 4.1.2 on 2023-12-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_info', '0010_proje_dosyalari'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeler',
            name='blog_bilgisi',
            field=models.ManyToManyField(blank=True, null=True, to='site_info.bloglar'),
        ),
    ]
