# Generated by Django 4.1.2 on 2023-12-29 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_info', '0011_projeler_blog_bilgisi'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeler',
            name='kayit_tarihi',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
