# Generated by Django 4.1.2 on 2023-12-30 00:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('site_info', '0013_projeler_silinme_bilgisi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proje_dosyalari',
            name='dosya',
            field=models.FileField(blank=True, null=True, upload_to='proje_dosyalari/', verbose_name='Dosya Adı'),
        ),
        migrations.CreateModel(
            name='taseronlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taseron_adi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Taşeron Adı')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email adresi')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('silinme_bilgisi', models.BooleanField(default=False)),
                ('proje_bilgisi', models.ManyToManyField(blank=True, null=True, to='site_info.projeler')),
                ('taseron_ait_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Proje Ait Olduğu')),
            ],
        ),
        migrations.CreateModel(
            name='taseron_sozlesme_dosyalari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosya', models.FileField(blank=True, null=True, upload_to='taseron_sozlesme/', verbose_name='Dosya Adı')),
                ('proje_ait_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_info.taseronlar', verbose_name='Proje Ait Olduğu')),
            ],
        ),
    ]
