# Generated by Django 4.1.2 on 2023-12-30 00:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muhasebe', '0013_alter_virman_virman_tarihi'),
        ('site_info', '0014_alter_proje_dosyalari_dosya_taseronlar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cari_taseron_baglantisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('silinme_bilgisi', models.BooleanField(default=False)),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('cari_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='muhasebe.cari', verbose_name='Cari Bilgisi')),
                ('gelir_kime_ait_oldugu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_info.taseronlar', verbose_name='Gelir Kategorisi Ait Olduğu')),
            ],
        ),
    ]
