# Generated by Django 4.1.2 on 2023-12-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_info', '0016_taseron_sozlesme_dosyalari_aciklama_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taseronlar',
            name='telefon_numarasi',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Telefon Numarası'),
        ),
    ]
