# Generated by Django 4.1.2 on 2024-01-01 02:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_info', '0018_alter_taseron_sozlesme_dosyalari_durum'),
    ]

    operations = [
        migrations.CreateModel(
            name='taseron_hakedisles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosya', models.FileField(blank=True, null=True, upload_to='taseron_sozlesme/', verbose_name='Dosya Adı')),
                ('dosya_adi', models.CharField(blank=True, max_length=400, null=True, verbose_name='Sözleşme Adı')),
                ('tarih', models.DateField(blank=True, null=True, verbose_name='Proje Tarihi')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('durum', models.BooleanField(blank=True, default=True, null=True, verbose_name='Durum')),
                ('tutar', models.FloatField(default=0, verbose_name='Tutar')),
                ('fatura_numarasi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Fatura Numarası ')),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('silinme_bilgisi', models.BooleanField(default=False)),
                ('proje_ait_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_info.taseronlar', verbose_name='Proje Ait Olduğu')),
            ],
        ),
    ]
