# Generated by Django 4.1.2 on 2024-01-01 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('site_info', '0019_taseron_hakedisles'),
    ]

    operations = [
        migrations.CreateModel(
            name='klasorler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('klasor_adi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Klasor Adı')),
                ('dosya_sahibi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Proje Ait Olduğu')),
                ('klasor_adi_db', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='site_info.klasorler')),
            ],
        ),
    ]
