# Generated by Django 4.1.2 on 2024-01-01 02:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('site_info', '0020_klasorler'),
    ]

    operations = [
        migrations.CreateModel(
            name='klasor_dosyalari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosya', models.FileField(blank=True, null=True, upload_to='users_files/', verbose_name='Dosya Adı')),
                ('dosya_adi', models.CharField(blank=True, max_length=400, null=True, verbose_name='Sözleşme Adı')),
                ('tarih', models.DateField(blank=True, null=True, verbose_name='Proje Tarihi')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('silinme_bilgisi', models.BooleanField(default=False)),
                ('dosya_sahibi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Proje Ait Olduğu')),
                ('proje_ait_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_info.klasorler', verbose_name='Proje Ait Olduğu')),
            ],
        ),
    ]
