# Generated by Django 4.1.2 on 2024-01-01 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_info', '0021_klasor_dosyalari'),
    ]

    operations = [
        migrations.AddField(
            model_name='klasorler',
            name='kayit_tarihi',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='klasorler',
            name='silinme_bilgisi',
            field=models.BooleanField(default=False),
        ),
    ]
