# Generated by Django 4.1.2 on 2024-01-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_info', '0022_klasorler_kayit_tarihi_klasorler_silinme_bilgisi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klasor_dosyalari',
            name='dosya',
            field=models.FileField(blank=True, null=True, upload_to='klasor_dosyalari/', verbose_name='Dosya Adı'),
        ),
    ]
