# Generated by Django 4.1.2 on 2024-01-02 14:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('site_info', '0023_alter_klasor_dosyalari_dosya'),
    ]

    operations = [
        migrations.CreateModel(
            name='takvim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('takvim_turu', models.CharField(blank=True, max_length=200, null=True, verbose_name='Takvim Etkinlik Türü')),
                ('baslangic_tarihi', models.DateField(blank=True, null=True, verbose_name='Başlangıç Tarihi')),
                ('bitis_tarihi', models.DateField(blank=True, null=True, verbose_name='Bitiş Tarihi')),
                ('baslangic_saati', models.TimeField(blank=True, null=True, verbose_name='Başlangıç Tarihi')),
                ('bitis_saati', models.TimeField(blank=True, null=True, verbose_name='Başlangıç Tarihi')),
                ('takvim_lokasyon', models.CharField(blank=True, max_length=200, null=True, verbose_name='Takvim Etkinlik Türü')),
                ('aciklma', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('silinme_bilgisi', models.BooleanField(default=False)),
                ('dosya_sahibi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Proje Ait Olduğu')),
            ],
        ),
    ]
