# Generated by Django 4.1.2 on 2024-01-02 15:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('site_info', '0024_takvim'),
    ]

    operations = [
        migrations.CreateModel(
            name='YapilacakPlanlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=400, null=True, verbose_name='Adı')),
                ('teslim_tarihi', models.DateField(blank=True, null=True, verbose_name='Proje Tarihi')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('status', models.CharField(blank=True, max_length=200, null=True, verbose_name='Durum')),
                ('oncelik_durumu', models.CharField(blank=True, max_length=200, null=True, verbose_name='öncelik Adı')),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('silinme_bilgisi', models.BooleanField(default=False)),
                ('proje_ait_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Proje Ait Olduğu')),
                ('yapacaklar', models.ManyToManyField(blank=True, null=True, related_name='yapilacak_planlari', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
