# Generated by Django 4.1.2 on 2024-01-02 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('site_info', '0025_yapilacakplanlari'),
    ]

    operations = [
        migrations.CreateModel(
            name='YapilacakDosyalari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosya', models.FileField(blank=True, null=True, upload_to='yapilacak_dosyalari/', verbose_name='Dosya Adı')),
                ('dosya_sahibi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dosya_sahibi', to=settings.AUTH_USER_MODEL, verbose_name='Proje Ait Olduğu')),
                ('proje_ait_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todo_sahibi', to='site_info.yapilacakplanlari', verbose_name='Proje Ait Olduğu')),
            ],
        ),
    ]
