# Generated by Django 4.1.2 on 2024-01-08 12:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('site_info', '0027_isplaniplanlari_isplanidosyalari'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='takvim',
            new_name='Event',
        ),
    ]
