# Generated by Django 4.1.2 on 2024-01-12 15:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('site_info', '0028_rename_takvim_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isplanidosyalari',
            name='dosya_sahibi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dosya_sahibi_isplani_dosyalari', to=settings.AUTH_USER_MODEL, verbose_name='Proje Ait Olduğu'),
        ),
        migrations.AlterField(
            model_name='isplanidosyalari',
            name='proje_ait_bilgisi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dosya_sahibi_isplani_dosyalari', to='site_info.isplaniplanlari', verbose_name='Proje Ait Olduğu'),
        ),
        migrations.CreateModel(
            name='IsplaniPlanlariIlerleme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teslim_tarihi', models.DateField(blank=True, null=True, verbose_name='Proje Tarihi')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('status', models.CharField(blank=True, max_length=200, null=True, verbose_name='Durum')),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('silinme_bilgisi', models.BooleanField(default=False)),
                ('proje_ait_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Proje Ait Olduğu')),
                ('yapan_kisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='isplani_planlari_ilerleme_yapanlar', to=settings.AUTH_USER_MODEL, verbose_name='Yapan Kişi')),
            ],
        ),
        migrations.CreateModel(
            name='IsplaniIlerlemeDosyalari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosya', models.FileField(blank=True, null=True, upload_to='isplani_dosyalari/', verbose_name='Dosya Adı')),
                ('dosya_sahibi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dosya_sahibi_isplani_ilerleme_dosyalari', to=settings.AUTH_USER_MODEL, verbose_name='Proje Ait Olduğu')),
                ('proje_ait_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dosya_sahibi_isplani_ilerleme_dosyalari', to='site_info.isplaniplanlariilerleme', verbose_name='Proje Ait Olduğu')),
                ('yapan_kisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='isplani_ilerleme_dosyalari_yapanlar', to=settings.AUTH_USER_MODEL, verbose_name='Yapan Kişi')),
            ],
        ),
    ]
