# Generated by Django 4.1.2 on 2024-01-12 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_info', '0029_alter_isplanidosyalari_dosya_sahibi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isplaniplanlariilerleme',
            name='proje_ait_bilgisi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_info.isplaniplanlari', verbose_name='Proje Ait Olduğu'),
        ),
    ]
