# Generated by Django 4.1.2 on 2024-01-12 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_info', '0030_alter_isplaniplanlariilerleme_proje_ait_bilgisi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isplaniilerlemedosyalari',
            name='dosya_sahibi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dosya_sahibi_isplani_ilerleme_dosyalari', to='site_info.isplaniplanlari', verbose_name='Proje Ait Olduğu'),
        ),
    ]
