# Generated by Django 4.1.2 on 2024-06-15 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_info', '0032_remove_santiye_kat_sayisi_bloglar_kat_sayisi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='santiye',
            name='blog_adi',
        ),
        migrations.RemoveField(
            model_name='santiye',
            name='blog_sayisi',
        ),
    ]
