# Generated by Django 4.2.8 on 2024-06-15 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("site_info", "0033_remove_santiye_blog_adi_remove_santiye_blog_sayisi"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="santiye",
            name="baslangic_tarihi",
        ),
        migrations.RemoveField(
            model_name="santiye",
            name="tahmini_bitis_tarihi",
        ),
    ]
