# Generated by Django 4.2.8 on 2024-06-15 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_info", "0034_remove_santiye_baslangic_tarihi_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="birimler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Proje_tipi_adi",
                    models.CharField(
                        blank=True,
                        max_length=400,
                        null=True,
                        verbose_name="Proje Tipi Adı",
                    ),
                ),
                ("silinme_bilgisi", models.BooleanField(default=False)),
                (
                    "kayit_tarihi",
                    models.DateTimeField(default=datetime.datetime.now, null=True),
                ),
                ("durum_bilgisi", models.BooleanField(default=True)),
            ],
        ),
    ]
