# Generated by Django 4.2.8 on 2024-06-15 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("site_info", "0035_birimler"),
    ]

    operations = [
        migrations.AddField(
            model_name="santiye_kalemleri",
            name="birimi",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="site_info.birimler",
                verbose_name="santiye Ait Olduğu",
            ),
        ),
        migrations.AddField(
            model_name="santiye_kalemleri",
            name="metraj",
            field=models.FloatField(default=0, verbose_name="Metraj Bilgisi"),
        ),
        migrations.AlterField(
            model_name="birimler",
            name="Proje_tipi_adi",
            field=models.CharField(
                blank=True, max_length=400, null=True, verbose_name="Birim  Adı"
            ),
        ),
    ]
