# Generated by Django 4.2.8 on 2024-06-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "site_info",
            "0036_santiye_kalemleri_birimi_santiye_kalemleri_metraj_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="santiye_kalemleri",
            name="tutari",
            field=models.FloatField(default=0, verbose_name="Tutarı Bilgisi"),
        ),
    ]
