# Generated by Django 4.2.8 on 2024-06-19 14:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_info", "0037_santiye_kalemleri_tutari"),
    ]

    operations = [
        migrations.AddField(
            model_name="bloglar",
            name="baslangic_tarihi",
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name="bloglar",
            name="bitis_tarihi",
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name="bloglar",
            name="kayit_tarihi",
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
