# Generated by Django 4.2.8 on 2024-06-19 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("site_info", "0038_bloglar_baslangic_tarihi_bloglar_bitis_tarihi_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="santiye_kalemlerin_dagilisi",
            name="blog_bilgisi",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="site_info.bloglar",
                verbose_name="Blog Ait Olduğu",
            ),
        ),
        migrations.AlterField(
            model_name="santiye_kalemlerin_dagilisi",
            name="kalem_bilgisi",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="site_info.santiye_kalemleri",
                verbose_name="Kalem Ait Olduğu",
            ),
        ),
        migrations.AlterField(
            model_name="santiye_kalemlerin_dagilisi",
            name="proje_ait_bilgisi",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Proje Ait Olduğu",
            ),
        ),
        migrations.AlterField(
            model_name="santiye_kalemlerin_dagilisi",
            name="proje_santiye_Ait",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="site_info.santiye",
                verbose_name="santiye Ait Olduğu",
            ),
        ),
    ]
