# Generated by Django 4.2.13 on 2024-08-29 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_info', '0040_historicalyapilacakplanlari_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltaseron_hakedisles',
            name='durum',
        ),
        migrations.RemoveField(
            model_name='historicaltaseron_hakedisles',
            name='tutar',
        ),
        migrations.RemoveField(
            model_name='taseron_hakedisles',
            name='durum',
        ),
        migrations.RemoveField(
            model_name='taseron_hakedisles',
            name='tutar',
        ),
    ]
