# Generated by Django 4.2.13 on 2024-09-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_info', '0041_remove_historicaltaseron_hakedisles_durum_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taseronlar',
            name='proje_bilgisi',
        ),
        migrations.AddField(
            model_name='taseronlar',
            name='blog_bilgisi',
            field=models.ManyToManyField(blank=True, null=True, to='site_info.bloglar'),
        ),
        migrations.AddField(
            model_name='taseronlar',
            name='kalem_bilgisi',
            field=models.ManyToManyField(blank=True, null=True, to='site_info.santiye_kalemleri'),
        ),
    ]
