# Generated by Django 4.2.13 on 2024-09-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_info', '0042_remove_taseronlar_proje_bilgisi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taseronlar',
            name='blog_bilgisi',
        ),
        migrations.RemoveField(
            model_name='taseronlar',
            name='kalem_bilgisi',
        ),
        migrations.AddField(
            model_name='taseronlar',
            name='proje_bilgisi',
            field=models.ManyToManyField(blank=True, null=True, to='site_info.projeler'),
        ),
    ]
