# Generated by Django 4.2.13 on 2024-09-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_info', '0043_remove_taseronlar_blog_bilgisi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeler',
            name='kalem_bilgisi',
            field=models.ManyToManyField(blank=True, null=True, to='site_info.santiye_kalemleri'),
        ),
    ]
