# Generated by Django 4.2.13 on 2024-09-01 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_info', '0044_projeler_kalem_bilgisi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalprojeler',
            name='aciklama',
        ),
        migrations.RemoveField(
            model_name='historicalprojeler',
            name='durum',
        ),
        migrations.RemoveField(
            model_name='historicalprojeler',
            name='proje_Adi',
        ),
        migrations.RemoveField(
            model_name='historicalprojeler',
            name='tarih',
        ),
        migrations.RemoveField(
            model_name='projeler',
            name='aciklama',
        ),
        migrations.RemoveField(
            model_name='projeler',
            name='durum',
        ),
        migrations.RemoveField(
            model_name='projeler',
            name='proje_Adi',
        ),
        migrations.RemoveField(
            model_name='projeler',
            name='tarih',
        ),
    ]
