# Generated by Django 4.2.13 on 2024-09-01 18:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('site_info', '0046_historicalprojeler_blog_bilgisi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ust_yuklenici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taseron_adi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Taşeron Adı')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email adresi')),
                ('telefon_numarasi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Telefon Numarası')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('silinme_bilgisi', models.BooleanField(default=False)),
                ('taseron_ait_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Proje Ait Olduğu')),
            ],
        ),
        migrations.CreateModel(
            name='ust_yuklenici_dosyalari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosya', models.FileField(blank=True, null=True, upload_to='taseron_sozlesme/', verbose_name='Dosya Adı')),
                ('dosya_adi', models.CharField(blank=True, max_length=400, null=True, verbose_name='Sözleşme Adı')),
                ('tarih', models.DateField(blank=True, null=True, verbose_name='Proje Tarihi')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('durum', models.BooleanField(blank=True, default=True, null=True, verbose_name='Durum')),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('silinme_bilgisi', models.BooleanField(default=False)),
                ('proje_ait_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_info.ust_yuklenici', verbose_name='Proje Ait Olduğu')),
            ],
        ),
        migrations.CreateModel(
            name='Historicalust_yuklenici_dosyalari',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('dosya', models.TextField(blank=True, max_length=100, null=True, verbose_name='Dosya Adı')),
                ('dosya_adi', models.CharField(blank=True, max_length=400, null=True, verbose_name='Sözleşme Adı')),
                ('tarih', models.DateField(blank=True, null=True, verbose_name='Proje Tarihi')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('durum', models.BooleanField(blank=True, default=True, null=True, verbose_name='Durum')),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('silinme_bilgisi', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proje_ait_bilgisi', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='site_info.ust_yuklenici', verbose_name='Proje Ait Olduğu')),
            ],
            options={
                'verbose_name': 'historical ust_yuklenici_dosyalari',
                'verbose_name_plural': 'historical ust_yuklenici_dosyalaris',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Historicalust_yuklenici',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('taseron_adi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Taşeron Adı')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email adresi')),
                ('telefon_numarasi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Telefon Numarası')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('silinme_bilgisi', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('taseron_ait_bilgisi', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Proje Ait Olduğu')),
            ],
            options={
                'verbose_name': 'historical ust_yuklenici',
                'verbose_name_plural': 'historical ust_yuklenicis',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
