# Generated by Django 4.2.13 on 2024-09-01 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_info', '0047_ust_yuklenici_ust_yuklenici_dosyalari_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ust_yuklenici_dosyalari',
            name='dosya',
            field=models.FileField(blank=True, null=True, upload_to='ust_yuklenici_sozlesme/', verbose_name='Dosya Adı'),
        ),
    ]
