# Generated by Django 4.2.13 on 2024-09-13 19:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('site_info', '0048_alter_ust_yuklenici_dosyalari_dosya'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historicalgantt_verileri',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Gantt Adı')),
                ('progress', models.FloatField(default=0, verbose_name='İlerleme Druumu')),
                ('progressByWorklog', models.BooleanField(default=False)),
                ('relevance', models.IntegerField(default=0)),
                ('type_ver', models.CharField(default='', max_length=200)),
                ('typeId', models.CharField(default='', max_length=200)),
                ('description', models.CharField(default='', max_length=400)),
                ('code', models.CharField(default='', max_length=200)),
                ('level', models.IntegerField(default=0)),
                ('status', models.CharField(default='', max_length=200)),
                ('depends', models.CharField(default='', max_length=200)),
                ('canWrite', models.BooleanField(default=True)),
                ('duration', models.FloatField(default=0)),
                ('start', models.DateField(blank=True, null=True, verbose_name='Başlangıç Tarihi')),
                ('bitis', models.DateField(blank=True, null=True, verbose_name='Bitiş Tarihi')),
                ('startIsMilestone', models.BooleanField(default=False)),
                ('endIsMilestone', models.BooleanField(default=False)),
                ('collapsed', models.BooleanField(default=False)),
                ('hasChild', models.BooleanField(default=False)),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('silinme_bilgisi', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('gantt_sahibi', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Gantt Sahibi')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical gantt_verileri',
                'verbose_name_plural': 'historical gantt_verileris',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='gantt_verileri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Gantt Adı')),
                ('progress', models.FloatField(default=0, verbose_name='İlerleme Druumu')),
                ('progressByWorklog', models.BooleanField(default=False)),
                ('relevance', models.IntegerField(default=0)),
                ('type_ver', models.CharField(default='', max_length=200)),
                ('typeId', models.CharField(default='', max_length=200)),
                ('description', models.CharField(default='', max_length=400)),
                ('code', models.CharField(default='', max_length=200)),
                ('level', models.IntegerField(default=0)),
                ('status', models.CharField(default='', max_length=200)),
                ('depends', models.CharField(default='', max_length=200)),
                ('canWrite', models.BooleanField(default=True)),
                ('duration', models.FloatField(default=0)),
                ('start', models.DateField(blank=True, null=True, verbose_name='Başlangıç Tarihi')),
                ('bitis', models.DateField(blank=True, null=True, verbose_name='Bitiş Tarihi')),
                ('startIsMilestone', models.BooleanField(default=False)),
                ('endIsMilestone', models.BooleanField(default=False)),
                ('collapsed', models.BooleanField(default=False)),
                ('hasChild', models.BooleanField(default=False)),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('silinme_bilgisi', models.BooleanField(default=False)),
                ('gantt_sahibi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gantt_sahibi', to=settings.AUTH_USER_MODEL, verbose_name='Gantt Sahibi')),
            ],
        ),
    ]
