# Generated by Django 4.2.13 on 2024-10-08 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_info', '0050_katman_historicalkatman'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalisplaniplanlari',
            name='katman',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='site_info.katman', verbose_name='Proje KAtmanı'),
        ),
        migrations.AddField(
            model_name='historicalisplaniplanlari',
            name='locasyon',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Lokasyon'),
        ),
        migrations.AddField(
            model_name='isplaniplanlari',
            name='katman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_info.katman', verbose_name='Proje KAtmanı'),
        ),
        migrations.AddField(
            model_name='isplaniplanlari',
            name='locasyon',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Lokasyon'),
        ),
    ]
