# Generated by Django 4.2.13 on 2024-10-08 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_info', '0051_historicalisplaniplanlari_katman_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalkatman',
            name='blog_bilgisi',
        ),
        migrations.RemoveField(
            model_name='historicalkatman',
            name='kalem_bilgisi',
        ),
        migrations.RemoveField(
            model_name='katman',
            name='blog_bilgisi',
        ),
        migrations.RemoveField(
            model_name='katman',
            name='kalem_bilgisi',
        ),
    ]
