# Generated by Django 4.2.13 on 2024-10-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_info', '0052_remove_historicalkatman_blog_bilgisi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalkatman',
            name='katman_adi',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Katman Adı'),
        ),
        migrations.AddField(
            model_name='katman',
            name='katman_adi',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Katman Adı'),
        ),
    ]
