# Generated by Django 4.2.13 on 2024-10-11 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_info', '0053_historicalkatman_katman_adi_katman_katman_adi'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalisplaniplanlari',
            name='blok',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='site_info.bloglar', verbose_name='Proje bloglari'),
        ),
        migrations.AddField(
            model_name='historicalisplaniplanlari',
            name='kat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='isplaniplanlari',
            name='blok',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_info.bloglar', verbose_name='Proje bloglari'),
        ),
        migrations.AddField(
            model_name='isplaniplanlari',
            name='kat',
            field=models.IntegerField(default=0),
        ),
    ]
