# Generated by Django 4.2.13 on 2024-10-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_info', '0054_historicalisplaniplanlari_blok_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsantiye',
            name='lat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalsantiye',
            name='lon',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='santiye',
            name='lat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='santiye',
            name='lon',
            field=models.TextField(blank=True, null=True),
        ),
    ]
