# Generated by Django 4.2.13 on 2024-10-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_info', '0055_historicalsantiye_lat_historicalsantiye_lon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalisplanidosyalari',
            name='pin',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='pinmi'),
        ),
        migrations.AddField(
            model_name='isplanidosyalari',
            name='pin',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='pinmi'),
        ),
    ]
