# Generated by Django 4.2.13 on 2024-10-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_info', '0056_historicalisplanidosyalari_pin_isplanidosyalari_pin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalisplaniplanlari',
            old_name='locasyon',
            new_name='locasyonx',
        ),
        migrations.RenameField(
            model_name='isplaniplanlari',
            old_name='locasyon',
            new_name='locasyonx',
        ),
        migrations.AddField(
            model_name='historicalisplaniplanlari',
            name='locasyony',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Lokasyon'),
        ),
        migrations.AddField(
            model_name='isplaniplanlari',
            name='locasyony',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Lokasyon'),
        ),
    ]
