# Generated by Django 4.2.13 on 2024-11-07 02:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0047_historicalpersonel_izinleri_gant_duzenleme_and_more'),
        ('muhasebe', '0056_faturalar_icin_bilgiler_gunluk_calisma_saati_and_more'),
        ('site_info', '0058_historicalgantt_olayi_gantt_olayi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historicalgenel_rapor',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('hava_durumu_sicaklik', models.FloatField(blank=True, null=True, verbose_name='hava_durumu Sıcaklık')),
                ('hava_durumu_ruzgar', models.FloatField(blank=True, null=True, verbose_name='hava_durumu rüzgar')),
                ('urun_adeti', models.FloatField(blank=True, null=True, verbose_name='Ürün Adeti')),
                ('personel_sayisi', models.FloatField(blank=True, null=True, verbose_name='Personel Sayısı')),
                ('imalat_aciklama', models.TextField()),
                ('genel_aciklama', models.TextField()),
                ('tarih', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('imalet_kalemi', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='site_info.santiye_kalemleri', verbose_name='Kalem Ait Olduğu')),
                ('personel_departmani', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.calisanlar_kategorisi', verbose_name='Gelen Ürün')),
                ('proje_ait_bilgisi', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Proje Ait Olduğu')),
                ('proje_santiye_Ait', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='site_info.santiye', verbose_name='santiye Ait Olduğu')),
                ('urun', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='muhasebe.urunler', verbose_name='Gelen Ürün')),
            ],
            options={
                'verbose_name': 'historical genel_rapor',
                'verbose_name_plural': 'historical genel_rapors',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='genel_rapor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hava_durumu_sicaklik', models.FloatField(blank=True, null=True, verbose_name='hava_durumu Sıcaklık')),
                ('hava_durumu_ruzgar', models.FloatField(blank=True, null=True, verbose_name='hava_durumu rüzgar')),
                ('urun_adeti', models.FloatField(blank=True, null=True, verbose_name='Ürün Adeti')),
                ('personel_sayisi', models.FloatField(blank=True, null=True, verbose_name='Personel Sayısı')),
                ('imalat_aciklama', models.TextField()),
                ('genel_aciklama', models.TextField()),
                ('tarih', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('imalet_kalemi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_info.santiye_kalemleri', verbose_name='Kalem Ait Olduğu')),
                ('personel_departmani', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.calisanlar_kategorisi', verbose_name='Gelen Ürün')),
                ('proje_ait_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Proje Ait Olduğu')),
                ('proje_santiye_Ait', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_info.santiye', verbose_name='santiye Ait Olduğu')),
                ('urun', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='muhasebe.urunler', verbose_name='Gelen Ürün')),
            ],
        ),
    ]
