# Generated by Django 4.2.13 on 2024-11-07 02:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('muhasebe', '0056_faturalar_icin_bilgiler_gunluk_calisma_saati_and_more'),
        ('users', '0047_historicalpersonel_izinleri_gant_duzenleme_and_more'),
        ('site_info', '0059_historicalgenel_rapor_genel_rapor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genel_rapor',
            name='genel_aciklama',
        ),
        migrations.RemoveField(
            model_name='genel_rapor',
            name='imalat_aciklama',
        ),
        migrations.RemoveField(
            model_name='genel_rapor',
            name='imalet_kalemi',
        ),
        migrations.RemoveField(
            model_name='genel_rapor',
            name='personel_departmani',
        ),
        migrations.RemoveField(
            model_name='genel_rapor',
            name='personel_sayisi',
        ),
        migrations.RemoveField(
            model_name='genel_rapor',
            name='urun',
        ),
        migrations.RemoveField(
            model_name='genel_rapor',
            name='urun_adeti',
        ),
        migrations.RemoveField(
            model_name='historicalgenel_rapor',
            name='genel_aciklama',
        ),
        migrations.RemoveField(
            model_name='historicalgenel_rapor',
            name='imalat_aciklama',
        ),
        migrations.RemoveField(
            model_name='historicalgenel_rapor',
            name='imalet_kalemi',
        ),
        migrations.RemoveField(
            model_name='historicalgenel_rapor',
            name='personel_departmani',
        ),
        migrations.RemoveField(
            model_name='historicalgenel_rapor',
            name='personel_sayisi',
        ),
        migrations.RemoveField(
            model_name='historicalgenel_rapor',
            name='urun',
        ),
        migrations.RemoveField(
            model_name='historicalgenel_rapor',
            name='urun_adeti',
        ),
        migrations.CreateModel(
            name='Historicalgenel_personel',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('personel_sayisi', models.FloatField(blank=True, null=True, verbose_name='Personel Sayısı')),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('hangi_rapor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Proje Ait Olduğu')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('personel_departmani', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.calisanlar_kategorisi', verbose_name='Gelen Ürün')),
                ('proje_ait_bilgisi', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='site_info.genel_rapor', verbose_name='Proje Ait Olduğu')),
            ],
            options={
                'verbose_name': 'historical genel_personel',
                'verbose_name_plural': 'historical genel_personels',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Historicalgenel_imalat',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('imalat_aciklama', models.TextField()),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('hangi_rapor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Proje Ait Olduğu')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('imalet_kalemi', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='site_info.santiye_kalemleri', verbose_name='Kalem Ait Olduğu')),
                ('proje_ait_bilgisi', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='site_info.genel_rapor', verbose_name='Proje Ait Olduğu')),
            ],
            options={
                'verbose_name': 'historical genel_imalat',
                'verbose_name_plural': 'historical genel_imalats',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Historicalgenel_aciklamalar',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('genel_aciklama', models.TextField()),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('hangi_rapor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Proje Ait Olduğu')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proje_ait_bilgisi', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='site_info.genel_rapor', verbose_name='Proje Ait Olduğu')),
            ],
            options={
                'verbose_name': 'historical genel_aciklamalar',
                'verbose_name_plural': 'historical genel_aciklamalars',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Historicalgelen_malzeme',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('urun_adeti', models.FloatField(blank=True, null=True, verbose_name='Ürün Adeti')),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('hangi_rapor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Proje Ait Olduğu')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proje_ait_bilgisi', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='site_info.genel_rapor', verbose_name='Proje Ait Olduğu')),
                ('urun', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='muhasebe.urunler', verbose_name='Gelen Ürün')),
            ],
            options={
                'verbose_name': 'historical gelen_malzeme',
                'verbose_name_plural': 'historical gelen_malzemes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='genel_personel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personel_sayisi', models.FloatField(blank=True, null=True, verbose_name='Personel Sayısı')),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('hangi_rapor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Proje Ait Olduğu')),
                ('personel_departmani', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.calisanlar_kategorisi', verbose_name='Gelen Ürün')),
                ('proje_ait_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_info.genel_rapor', verbose_name='Proje Ait Olduğu')),
            ],
        ),
        migrations.CreateModel(
            name='genel_imalat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imalat_aciklama', models.TextField()),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('hangi_rapor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Proje Ait Olduğu')),
                ('imalet_kalemi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_info.santiye_kalemleri', verbose_name='Kalem Ait Olduğu')),
                ('proje_ait_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_info.genel_rapor', verbose_name='Proje Ait Olduğu')),
            ],
        ),
        migrations.CreateModel(
            name='genel_aciklamalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genel_aciklama', models.TextField()),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('hangi_rapor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Proje Ait Olduğu')),
                ('proje_ait_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_info.genel_rapor', verbose_name='Proje Ait Olduğu')),
            ],
        ),
        migrations.CreateModel(
            name='gelen_malzeme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urun_adeti', models.FloatField(blank=True, null=True, verbose_name='Ürün Adeti')),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('hangi_rapor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Proje Ait Olduğu')),
                ('proje_ait_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_info.genel_rapor', verbose_name='Proje Ait Olduğu')),
                ('urun', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='muhasebe.urunler', verbose_name='Gelen Ürün')),
            ],
        ),
    ]
