# Generated by Django 4.2.13 on 2024-11-07 03:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('site_info', '0060_remove_genel_rapor_genel_aciklama_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genel_rapor',
            name='hava_durumu_ruzgar',
        ),
        migrations.RemoveField(
            model_name='genel_rapor',
            name='hava_durumu_sicaklik',
        ),
        migrations.RemoveField(
            model_name='historicalgenel_rapor',
            name='hava_durumu_ruzgar',
        ),
        migrations.RemoveField(
            model_name='historicalgenel_rapor',
            name='hava_durumu_sicaklik',
        ),
        migrations.CreateModel(
            name='Historicalgenel_hava_durumu',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('hava_durumu_sicaklik', models.FloatField(blank=True, null=True, verbose_name='hava_durumu Sıcaklık')),
                ('hava_durumu_ruzgar', models.FloatField(blank=True, null=True, verbose_name='hava_durumu rüzgar')),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('hangi_rapor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Proje Ait Olduğu')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proje_ait_bilgisi', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='site_info.genel_rapor', verbose_name='Proje Ait Olduğu')),
            ],
            options={
                'verbose_name': 'historical genel_hava_durumu',
                'verbose_name_plural': 'historical genel_hava_durumus',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='genel_hava_durumu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hava_durumu_sicaklik', models.FloatField(blank=True, null=True, verbose_name='hava_durumu Sıcaklık')),
                ('hava_durumu_ruzgar', models.FloatField(blank=True, null=True, verbose_name='hava_durumu rüzgar')),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('hangi_rapor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Proje Ait Olduğu')),
                ('proje_ait_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_info.genel_rapor', verbose_name='Proje Ait Olduğu')),
            ],
        ),
    ]
