# Generated by Django 4.2.13 on 2024-11-07 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('site_info', '0061_remove_genel_rapor_hava_durumu_ruzgar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genel_rapor',
            name='raporu_olusturan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raporu_olusturan', to=settings.AUTH_USER_MODEL, verbose_name='Proje Ait Olduğu'),
        ),
        migrations.AddField(
            model_name='historicalgenel_rapor',
            name='raporu_olusturan',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Proje Ait Olduğu'),
        ),
    ]
