# Generated by Django 4.2.13 on 2024-11-10 16:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('site_info', '0063_genel_rapor_silinme_bilgisi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genel_rapor',
            name='onaylama_tarihi',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='genel_rapor',
            name='raporu_onaylayan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raporu_onaylayan', to=settings.AUTH_USER_MODEL, verbose_name='Proje Ait Olduğu'),
        ),
        migrations.AddField(
            model_name='historicalgenel_rapor',
            name='onaylama_tarihi',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='historicalgenel_rapor',
            name='raporu_onaylayan',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Proje Ait Olduğu'),
        ),
    ]
