# Generated by Django 4.2.13 on 2024-11-26 15:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('site_info', '0064_genel_rapor_onaylama_tarihi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='musteri_bilgisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musteri_adi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Müşteri Adı ')),
                ('musteri_soyadi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Müşteri Soyadı ')),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('musteri_kime_ait', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Proje Ait Olduğu')),
            ],
        ),
        migrations.CreateModel(
            name='Historicalmusteri_bilgisi',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('musteri_adi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Müşteri Adı ')),
                ('musteri_soyadi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Müşteri Soyadı ')),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('musteri_kime_ait', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Proje Ait Olduğu')),
            ],
            options={
                'verbose_name': 'historical musteri_bilgisi',
                'verbose_name_plural': 'historical musteri_bilgisis',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Historicaldaire_bilgisi',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('kat', models.FloatField(default=1, verbose_name='Kat Bilgisi')),
                ('daire_no', models.CharField(blank=True, max_length=200, null=True, verbose_name='Daire No')),
                ('oda_sayisi', models.FloatField(default=1, verbose_name='Oda Sayısı')),
                ('metre_kare_brut', models.FloatField(default=1, verbose_name='Metre Kare ')),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('blog_bilgisi', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='site_info.bloglar', verbose_name='santiye Ait Olduğu')),
                ('daire_kime_ait', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Proje Ait Olduğu')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical daire_bilgisi',
                'verbose_name_plural': 'historical daire_bilgisis',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='daire_bilgisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kat', models.FloatField(default=1, verbose_name='Kat Bilgisi')),
                ('daire_no', models.CharField(blank=True, max_length=200, null=True, verbose_name='Daire No')),
                ('oda_sayisi', models.FloatField(default=1, verbose_name='Oda Sayısı')),
                ('metre_kare_brut', models.FloatField(default=1, verbose_name='Metre Kare ')),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('blog_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_info.bloglar', verbose_name='santiye Ait Olduğu')),
                ('daire_kime_ait', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Proje Ait Olduğu')),
            ],
        ),
    ]
