# Generated by Django 4.2.13 on 2024-11-28 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_info', '0066_musteri_daire_baglama_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genel_rapor',
            name='bitis_tarih',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='genel_rapor',
            name='kayip_gun_aciklamasi',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Kayıp Gün Açıklaması'),
        ),
        migrations.AddField(
            model_name='genel_rapor',
            name='kayip_gun_sayisi',
            field=models.IntegerField(default=0, verbose_name='Kayıp Gün Sayısı'),
        ),
        migrations.AddField(
            model_name='genel_rapor',
            name='kayip_gun_sebebi',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='historicalgenel_rapor',
            name='bitis_tarih',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='historicalgenel_rapor',
            name='kayip_gun_aciklamasi',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Kayıp Gün Açıklaması'),
        ),
        migrations.AddField(
            model_name='historicalgenel_rapor',
            name='kayip_gun_sayisi',
            field=models.IntegerField(default=0, verbose_name='Kayıp Gün Sayısı'),
        ),
        migrations.AddField(
            model_name='historicalgenel_rapor',
            name='kayip_gun_sebebi',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='0', max_length=200),
        ),
    ]
