# Generated by Django 4.2.13 on 2024-12-10 13:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('site_info', '0067_genel_rapor_bitis_tarih_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genel_rapor',
            name='kayip_gun_sebebi',
            field=models.CharField(choices=[('-1', '-1'), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalgenel_rapor',
            name='kayip_gun_sebebi',
            field=models.CharField(choices=[('-1', '-1'), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='0', max_length=200),
        ),
        migrations.CreateModel(
            name='talep_ve_sikayet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sikayet_nedeni', models.CharField(blank=True, max_length=10, null=True, verbose_name='Şikayet_nedeni')),
                ('sikayet_aciklamasi', models.TextField()),
                ('talep_sikayet_ayrimi', models.CharField(choices=[('0', '0'), ('1', '1')], default='0', max_length=100)),
                ('durum', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2')], default='0', max_length=100)),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('musteri', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_info.musteri_bilgisi', verbose_name='Proje Ait Olduğu')),
                ('sikayet_kime_ait', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Proje Ait Olduğu')),
            ],
        ),
        migrations.CreateModel(
            name='Historicaltalep_ve_sikayet',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('sikayet_nedeni', models.CharField(blank=True, max_length=10, null=True, verbose_name='Şikayet_nedeni')),
                ('sikayet_aciklamasi', models.TextField()),
                ('talep_sikayet_ayrimi', models.CharField(choices=[('0', '0'), ('1', '1')], default='0', max_length=100)),
                ('durum', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2')], default='0', max_length=100)),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('musteri', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='site_info.musteri_bilgisi', verbose_name='Proje Ait Olduğu')),
                ('sikayet_kime_ait', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Proje Ait Olduğu')),
            ],
            options={
                'verbose_name': 'historical talep_ve_sikayet',
                'verbose_name_plural': 'historical talep_ve_sikayets',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
