# Generated by Django 4.2.13 on 2024-12-10 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_info', '0068_alter_genel_rapor_kayip_gun_sebebi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltalep_ve_sikayet',
            name='islem_tarihi',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='talep_ve_sikayet',
            name='islem_tarihi',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
