# Generated by Django 4.2.13 on 2024-12-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_info', '0069_historicaltalep_ve_sikayet_islem_tarihi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmusteri_bilgisi',
            name='musteri_telefon_numarasi',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Telefon Numarası'),
        ),
        migrations.AddField(
            model_name='musteri_bilgisi',
            name='musteri_telefon_numarasi',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Telefon Numarası'),
        ),
    ]
