# Generated by Django 4.2.13 on 2024-12-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_info', '0071_alter_daire_bilgisi_kat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmusteri_daire_baglama',
            name='durum',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2')], default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='musteri_daire_baglama',
            name='durum',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2')], default='0', max_length=100),
        ),
    ]
