# Generated by Django 4.2.13 on 2024-12-14 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_info', '0072_historicalmusteri_daire_baglama_durum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltalep_ve_sikayet',
            name='daire',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='site_info.daire_bilgisi', verbose_name='Daire'),
        ),
        migrations.AddField(
            model_name='talep_ve_sikayet',
            name='daire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_info.daire_bilgisi', verbose_name='Daire'),
        ),
    ]
