# Generated by Django 4.2.13 on 2024-12-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_info', '0074_musteri_notlari_historicalmusteri_notlari'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmusteri_bilgisi',
            name='silinme_bilgisi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalmusteri_notlari',
            name='silinme_bilgisi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='musteri_bilgisi',
            name='silinme_bilgisi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='musteri_notlari',
            name='silinme_bilgisi',
            field=models.BooleanField(default=False),
        ),
    ]
