# Generated by Django 4.2.13 on 2024-12-21 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_info', '0076_musteri_evraklari_historicalmusteri_evraklari'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmusteri_evraklari',
            name='musterisi',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='site_info.musteri_bilgisi', verbose_name='Müşeterisi'),
        ),
        migrations.AddField(
            model_name='musteri_evraklari',
            name='musterisi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_info.musteri_bilgisi', verbose_name='Müşeterisi'),
        ),
    ]
