# Generated by Django 4.2.13 on 2024-12-21 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_info', '0077_historicalmusteri_evraklari_musterisi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltalep_ve_sikayet',
            name='silinme_bilgisi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='talep_ve_sikayet',
            name='silinme_bilgisi',
            field=models.BooleanField(default=False),
        ),
    ]
