# Generated by Django 4.2.13 on 2024-12-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_info', '0078_historicaltalep_ve_sikayet_silinme_bilgisi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmusteri_evraklari',
            name='kira_kontrati',
        ),
        migrations.RemoveField(
            model_name='historicalmusteri_evraklari',
            name='oturma_belgesi',
        ),
        migrations.RemoveField(
            model_name='musteri_evraklari',
            name='kira_kontrati',
        ),
        migrations.RemoveField(
            model_name='musteri_evraklari',
            name='oturma_belgesi',
        ),
        migrations.AddField(
            model_name='historicalmusteri_evraklari',
            name='evrak',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='evrak'),
        ),
        migrations.AddField(
            model_name='historicalmusteri_evraklari',
            name='evrak_detayi',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Evrak Adı'),
        ),
        migrations.AddField(
            model_name='musteri_evraklari',
            name='evrak',
            field=models.FileField(blank=True, null=True, upload_to='evrak/', verbose_name='evrak'),
        ),
        migrations.AddField(
            model_name='musteri_evraklari',
            name='evrak_detayi',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Evrak Adı'),
        ),
    ]
