# Generated by Django 4.2.13 on 2024-12-21 15:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('site_info', '0079_remove_historicalmusteri_evraklari_kira_kontrati_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='teklifler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toplam_tutar', models.FloatField(default=0, verbose_name='Toplam Tutar')),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('musterisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_info.musteri_bilgisi', verbose_name='Müşeterisi')),
                ('teklif_kime_ait', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teklif_kime_ait', to=settings.AUTH_USER_MODEL, verbose_name='Proje Ait Olduğu')),
            ],
        ),
        migrations.CreateModel(
            name='teklif_icerikleri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urun_hizmet', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ürün Başlığı')),
                ('urun_aciklama', models.CharField(blank=True, max_length=400, null=True, verbose_name='Ürün Açıklama')),
                ('indirim', models.FloatField(default=0, verbose_name='İndirim Oranı')),
                ('miktar', models.FloatField(default=0, verbose_name='Miktar')),
                ('birim_fiyati', models.FloatField(default=0, verbose_name='Birim Fİyati')),
                ('genel_toplam', models.FloatField(default=0, verbose_name='Genel Toplam')),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('hangi_teklif', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_info.teklifler', verbose_name='Teklif ')),
                ('kime_ait', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Proje Ait Olduğu')),
            ],
        ),
        migrations.CreateModel(
            name='Historicalteklifler',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('toplam_tutar', models.FloatField(default=0, verbose_name='Toplam Tutar')),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('musterisi', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='site_info.musteri_bilgisi', verbose_name='Müşeterisi')),
                ('teklif_kime_ait', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Proje Ait Olduğu')),
            ],
            options={
                'verbose_name': 'historical teklifler',
                'verbose_name_plural': 'historical tekliflers',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Historicalteklif_icerikleri',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('urun_hizmet', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ürün Başlığı')),
                ('urun_aciklama', models.CharField(blank=True, max_length=400, null=True, verbose_name='Ürün Açıklama')),
                ('indirim', models.FloatField(default=0, verbose_name='İndirim Oranı')),
                ('miktar', models.FloatField(default=0, verbose_name='Miktar')),
                ('birim_fiyati', models.FloatField(default=0, verbose_name='Birim Fİyati')),
                ('genel_toplam', models.FloatField(default=0, verbose_name='Genel Toplam')),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('hangi_teklif', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='site_info.teklifler', verbose_name='Teklif ')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('kime_ait', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Proje Ait Olduğu')),
            ],
            options={
                'verbose_name': 'historical teklif_icerikleri',
                'verbose_name_plural': 'historical teklif_icerikleris',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
