# Generated by Django 4.2.13 on 2024-12-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_info', '0080_teklifler_teklif_icerikleri_historicalteklifler_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalteklifler',
            name='durum',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2')], default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='historicalteklifler',
            name='teklif_basligi',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Teklif Başlığı'),
        ),
        migrations.AddField(
            model_name='teklifler',
            name='durum',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2')], default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='teklifler',
            name='teklif_basligi',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Teklif Başlığı'),
        ),
    ]
