# Generated by Django 4.2.13 on 2024-12-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_info', '0081_historicalteklifler_durum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalteklif_icerikleri',
            name='birim_fiyati_ıqd',
            field=models.FloatField(default=0, verbose_name='Birim Fİyati'),
        ),
        migrations.AddField(
            model_name='teklif_icerikleri',
            name='birim_fiyati_ıqd',
            field=models.FloatField(default=0, verbose_name='Birim Fİyati'),
        ),
    ]
