# Generated by Django 4.2.13 on 2024-12-26 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_info', '0083_alter_historicalmusteri_notlari_musterisi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmusteri_evraklari',
            name='silinme_bilgisi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='musteri_evraklari',
            name='silinme_bilgisi',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicalmusteri_evraklari',
            name='evrak',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Evrak'),
        ),
        migrations.AlterField(
            model_name='historicalmusteri_evraklari',
            name='musterisi',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='site_info.musteri_bilgisi', verbose_name='Müşterisi'),
        ),
        migrations.AlterField(
            model_name='musteri_evraklari',
            name='evrak',
            field=models.FileField(blank=True, null=True, upload_to='evrak/', verbose_name='Evrak'),
        ),
        migrations.AlterField(
            model_name='musteri_evraklari',
            name='musterisi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_info.musteri_bilgisi', verbose_name='Müşterisi'),
        ),
    ]
