# Generated by Django 4.2.13 on 2025-01-01 21:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('site_info', '0084_historicalmusteri_evraklari_silinme_bilgisi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='bina_goruntuleri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ondden_goruntu', models.FileField(blank=True, null=True, upload_to='bina_goruntuleri/', verbose_name='Önden Görüntü')),
                ('arkadan_goruntu', models.FileField(blank=True, null=True, upload_to='bina_goruntuleri/', verbose_name='Arka Görüntü')),
                ('sagdan_goruntu', models.FileField(blank=True, null=True, upload_to='bina_goruntuleri/', verbose_name='Sağdan Görüntü')),
                ('soldan_goruntu', models.FileField(blank=True, null=True, upload_to='bina_goruntuleri/', verbose_name='Soldan Görüntü')),
                ('ustten_goruntu', models.FileField(blank=True, null=True, upload_to='bina_goruntuleri/', verbose_name='Üstten Görüntü')),
                ('alttan_goruntu', models.FileField(blank=True, null=True, upload_to='bina_goruntuleri/', verbose_name='Alttan Görüntü')),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Historicalbina_goruntuleri',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('ondden_goruntu', models.TextField(blank=True, max_length=100, null=True, verbose_name='Önden Görüntü')),
                ('arkadan_goruntu', models.TextField(blank=True, max_length=100, null=True, verbose_name='Arka Görüntü')),
                ('sagdan_goruntu', models.TextField(blank=True, max_length=100, null=True, verbose_name='Sağdan Görüntü')),
                ('soldan_goruntu', models.TextField(blank=True, max_length=100, null=True, verbose_name='Soldan Görüntü')),
                ('ustten_goruntu', models.TextField(blank=True, max_length=100, null=True, verbose_name='Üstten Görüntü')),
                ('alttan_goruntu', models.TextField(blank=True, max_length=100, null=True, verbose_name='Alttan Görüntü')),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical bina_goruntuleri',
                'verbose_name_plural': 'historical bina_goruntuleris',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='historicalsantiye',
            name='bina_goruntuleri_aitlik',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='site_info.bina_goruntuleri', verbose_name='Bina Görüntüleri'),
        ),
        migrations.AddField(
            model_name='santiye',
            name='bina_goruntuleri_aitlik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_info.bina_goruntuleri', verbose_name='Bina Görüntüleri'),
        ),
    ]
