# Generated by Django 4.2.13 on 2025-01-02 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_info', '0085_bina_goruntuleri_historicalbina_goruntuleri_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bina_goruntuleri',
            name='isimi',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Görüntü Adı'),
        ),
        migrations.AddField(
            model_name='historicalbina_goruntuleri',
            name='isimi',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Görüntü Adı'),
        ),
    ]
