# Generated by Django 4.2.13 on 2025-01-07 02:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('site_info', '0086_bina_goruntuleri_isimi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='santiye_sablonlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sablon_adi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Sablon Adı')),
                ('sablon_durumu', models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2')], max_length=200, null=True, verbose_name='Sablon Durumu')),
                ('silinme_bilgisi', models.BooleanField(default=False)),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('proje_ait_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Proje Ait Olduğu')),
                ('proje_santiye_Ait', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_info.santiye', verbose_name='santiye Ait Olduğu')),
            ],
        ),
        migrations.CreateModel(
            name='sanytiye_sablon_bolumleri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bolum', models.CharField(blank=True, max_length=200, null=True, verbose_name='Sablon Bölüm Adı')),
                ('silinme_bilgisi', models.BooleanField(default=False)),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('proje_ait_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Proje Ait Olduğu')),
                ('proje_santiye_Ait', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_info.santiye', verbose_name='santiye Ait Olduğu')),
                ('sablon_adi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_info.santiye_sablonlari', verbose_name='Sablon Ait Olduğu')),
            ],
        ),
        migrations.CreateModel(
            name='santiye_imalat_kalemleri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icerik', models.CharField(blank=True, max_length=200, null=True, verbose_name='İçerik Adı')),
                ('is_grubu', models.CharField(blank=True, max_length=200, null=True, verbose_name='İçerik Adı')),
                ('silinme_bilgisi', models.BooleanField(default=False)),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('detay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_info.sanytiye_sablon_bolumleri', verbose_name='Detay Ait Olduğu')),
                ('proje_ait_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Proje Ait Olduğu')),
                ('proje_santiye_Ait', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_info.santiye', verbose_name='santiye Ait Olduğu')),
            ],
        ),
        migrations.CreateModel(
            name='imalat_kalemleri_imalat_detaylari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imalat_detayi', models.CharField(blank=True, max_length=200, null=True, verbose_name='İmalat Detayı')),
                ('silinme_bilgisi', models.BooleanField(default=False)),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('icerik', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_info.santiye_imalat_kalemleri', verbose_name='İçerik Ait Olduğu')),
                ('proje_ait_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Proje Ait Olduğu')),
                ('proje_santiye_Ait', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_info.santiye', verbose_name='santiye Ait Olduğu')),
            ],
        ),
        migrations.CreateModel(
            name='Historicalsanytiye_sablon_bolumleri',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('bolum', models.CharField(blank=True, max_length=200, null=True, verbose_name='Sablon Bölüm Adı')),
                ('silinme_bilgisi', models.BooleanField(default=False)),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proje_ait_bilgisi', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Proje Ait Olduğu')),
                ('proje_santiye_Ait', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='site_info.santiye', verbose_name='santiye Ait Olduğu')),
                ('sablon_adi', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='site_info.santiye_sablonlari', verbose_name='Sablon Ait Olduğu')),
            ],
            options={
                'verbose_name': 'historical sanytiye_sablon_bolumleri',
                'verbose_name_plural': 'historical sanytiye_sablon_bolumleris',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Historicalsantiye_sablonlari',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('sablon_adi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Sablon Adı')),
                ('sablon_durumu', models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2')], max_length=200, null=True, verbose_name='Sablon Durumu')),
                ('silinme_bilgisi', models.BooleanField(default=False)),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proje_ait_bilgisi', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Proje Ait Olduğu')),
                ('proje_santiye_Ait', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='site_info.santiye', verbose_name='santiye Ait Olduğu')),
            ],
            options={
                'verbose_name': 'historical santiye_sablonlari',
                'verbose_name_plural': 'historical santiye_sablonlaris',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Historicalsantiye_imalat_kalemleri',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('icerik', models.CharField(blank=True, max_length=200, null=True, verbose_name='İçerik Adı')),
                ('is_grubu', models.CharField(blank=True, max_length=200, null=True, verbose_name='İçerik Adı')),
                ('silinme_bilgisi', models.BooleanField(default=False)),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('detay', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='site_info.sanytiye_sablon_bolumleri', verbose_name='Detay Ait Olduğu')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proje_ait_bilgisi', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Proje Ait Olduğu')),
                ('proje_santiye_Ait', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='site_info.santiye', verbose_name='santiye Ait Olduğu')),
            ],
            options={
                'verbose_name': 'historical santiye_imalat_kalemleri',
                'verbose_name_plural': 'historical santiye_imalat_kalemleris',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Historicalimalat_kalemleri_imalat_detaylari',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('imalat_detayi', models.CharField(blank=True, max_length=200, null=True, verbose_name='İmalat Detayı')),
                ('silinme_bilgisi', models.BooleanField(default=False)),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('icerik', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='site_info.santiye_imalat_kalemleri', verbose_name='İçerik Ait Olduğu')),
                ('proje_ait_bilgisi', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Proje Ait Olduğu')),
                ('proje_santiye_Ait', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='site_info.santiye', verbose_name='santiye Ait Olduğu')),
            ],
            options={
                'verbose_name': 'historical imalat_kalemleri_imalat_detaylari',
                'verbose_name_plural': 'historical imalat_kalemleri_imalat_detaylaris',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
