# Generated by Django 4.2.13 on 2025-01-08 19:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('site_info', '0087_santiye_sablonlari_sanytiye_sablon_bolumleri_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkdaireleri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kat', models.IntegerField(default=1, verbose_name='Kat Bilgisi')),
                ('kat_daire_sayisi', models.IntegerField(default=1, verbose_name='Kat Bilgisi')),
                ('daire_no', models.CharField(blank=True, max_length=200, null=True, verbose_name='Daire No')),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('blog_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_info.bloglar', verbose_name='santiye Ait Olduğu')),
                ('proje_ait_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Proje Ait Olduğu')),
                ('proje_santiye_Ait', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_info.santiye', verbose_name='santiye Ait Olduğu')),
            ],
        ),
        migrations.CreateModel(
            name='imalat_daire_balama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamamlanma_bilgisi', models.BooleanField(default=False)),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('blog_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_info.bloglar', verbose_name='santiye Ait Olduğu')),
                ('daire_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_info.checkdaireleri', verbose_name='Daire Ait Olduğu')),
                ('imalat_detayi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_info.santiye_imalat_kalemleri', verbose_name='İmalat Detayı')),
                ('onaylayan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onaylayan', to=settings.AUTH_USER_MODEL, verbose_name='Onaylayan')),
                ('proje_ait_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Proje Ait Olduğu')),
                ('proje_santiye_Ait', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_info.santiye', verbose_name='santiye Ait Olduğu')),
                ('tamamlamayi_yapan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tamamlamayi_yapan', to=settings.AUTH_USER_MODEL, verbose_name='Tamamlamayı Yapan')),
            ],
        ),
        migrations.CreateModel(
            name='Historicalimalat_daire_balama',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('tamamlanma_bilgisi', models.BooleanField(default=False)),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('blog_bilgisi', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='site_info.bloglar', verbose_name='santiye Ait Olduğu')),
                ('daire_bilgisi', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='site_info.checkdaireleri', verbose_name='Daire Ait Olduğu')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('imalat_detayi', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='site_info.santiye_imalat_kalemleri', verbose_name='İmalat Detayı')),
                ('onaylayan', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Onaylayan')),
                ('proje_ait_bilgisi', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Proje Ait Olduğu')),
                ('proje_santiye_Ait', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='site_info.santiye', verbose_name='santiye Ait Olduğu')),
                ('tamamlamayi_yapan', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Tamamlamayı Yapan')),
            ],
            options={
                'verbose_name': 'historical imalat_daire_balama',
                'verbose_name_plural': 'historical imalat_daire_balamas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Historicalcheckdaireleri',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('kat', models.IntegerField(default=1, verbose_name='Kat Bilgisi')),
                ('kat_daire_sayisi', models.IntegerField(default=1, verbose_name='Kat Bilgisi')),
                ('daire_no', models.CharField(blank=True, max_length=200, null=True, verbose_name='Daire No')),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('blog_bilgisi', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='site_info.bloglar', verbose_name='santiye Ait Olduğu')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proje_ait_bilgisi', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Proje Ait Olduğu')),
                ('proje_santiye_Ait', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='site_info.santiye', verbose_name='santiye Ait Olduğu')),
            ],
            options={
                'verbose_name': 'historical checkdaireleri',
                'verbose_name_plural': 'historical checkdaireleris',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Historicalblog_ortak_alan_ve_cepheleri',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('aciklama_adi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Aciklama Adı')),
                ('bolum_icerigi', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2')], default='0', max_length=200, verbose_name='Bolum İçeriği')),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('blog_ait_bilgisi', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='site_info.bloglar', verbose_name='Blog Ait Olduğu')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proje_ait_bilgisi', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Proje Ait Olduğu')),
                ('proje_santiye_Ait', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='site_info.santiye', verbose_name='santiye Ait Olduğu')),
            ],
            options={
                'verbose_name': 'historical blog_ortak_alan_ve_cepheleri',
                'verbose_name_plural': 'historical blog_ortak_alan_ve_cepheleris',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='blog_ortak_alan_ve_cepheleri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aciklama_adi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Aciklama Adı')),
                ('bolum_icerigi', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2')], default='0', max_length=200, verbose_name='Bolum İçeriği')),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('blog_ait_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_info.bloglar', verbose_name='Blog Ait Olduğu')),
                ('proje_ait_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Proje Ait Olduğu')),
                ('proje_santiye_Ait', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_info.santiye', verbose_name='santiye Ait Olduğu')),
            ],
        ),
    ]
