# Generated by Django 4.2.13 on 2025-01-08 20:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('site_info', '0088_checkdaireleri_imalat_daire_balama_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkdaireleri',
            name='genel_notlar',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcheckdaireleri',
            name='genel_notlar',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Historicaldaire_resimleri_chjeckdaireleri',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('resim', models.TextField(blank=True, max_length=100, null=True, verbose_name='Resim Adı')),
                ('resim_aciklamasi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Resim Açıklaması')),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('daire_bilgisi', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='site_info.checkdaireleri', verbose_name='Daire Ait Olduğu')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical daire_resimleri_chjeckdaireleri',
                'verbose_name_plural': 'historical daire_resimleri_chjeckdaireleris',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='daire_resimleri_chjeckdaireleri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resim', models.FileField(blank=True, null=True, upload_to='daire_resimleri/', verbose_name='Resim Adı')),
                ('resim_aciklamasi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Resim Açıklaması')),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('daire_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_info.checkdaireleri', verbose_name='Daire Ait Olduğu')),
            ],
        ),
    ]
