# Generated by Django 4.2.13 on 2025-01-09 02:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_info', '0090_historicalimalat_daire_balama_tamamlama_tarihi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalimalat_daire_balama',
            name='tamamlama_tarihi',
        ),
        migrations.RemoveField(
            model_name='imalat_daire_balama',
            name='tamamlama_tarihi',
        ),
        migrations.AddField(
            model_name='historicalimalat_daire_balama',
            name='onaylama_notu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalimalat_daire_balama',
            name='onaylma_tarihi',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='historicalimalat_daire_balama',
            name='tarih',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='imalat_daire_balama',
            name='onaylama_notu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imalat_daire_balama',
            name='onaylma_tarihi',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='imalat_daire_balama',
            name='tarih',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
