# Generated by Django 4.2.13 on 2025-03-06 08:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_info', '0091_remove_historicalimalat_daire_balama_tamamlama_tarihi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalimalat_daire_balama',
            name='onaylma_tarihi',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalimalat_daire_balama',
            name='tarih',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='imalat_daire_balama',
            name='onaylma_tarihi',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='imalat_daire_balama',
            name='tarih',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
