# Generated by Django 4.2.13 on 2025-03-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_info', '0094_check_liste_onaylama_gruplari_tamamlanma_bilgisi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkdaireleri',
            name='dosya',
            field=models.FileField(blank=True, null=True, upload_to='daire_dosyalari/', verbose_name='Dosya Adı'),
        ),
        migrations.AddField(
            model_name='historicalcheckdaireleri',
            name='dosya',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Dosya Adı'),
        ),
    ]
