# Generated by Django 4.2.13 on 2025-03-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_info', '0095_checkdaireleri_dosya_historicalcheckdaireleri_dosya'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalimalat_daire_balama',
            name='dosya',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Dosya Adı'),
        ),
        migrations.AddField(
            model_name='historicalimalat_daire_balama',
            name='genel_notlar',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imalat_daire_balama',
            name='dosya',
            field=models.FileField(blank=True, null=True, upload_to='daire_dosyalari/', verbose_name='Dosya Adı'),
        ),
        migrations.AddField(
            model_name='imalat_daire_balama',
            name='genel_notlar',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
