# Generated by Django 4.2.13 on 2025-03-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_info', '0097_rfi_sablonlar_rfi_sablon_kalemleri_rfi_kontrol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrfi_sablonlar',
            name='rfi_kategorisi',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='RFI Başlık'),
        ),
        migrations.AddField(
            model_name='rfi_sablonlar',
            name='rfi_kategorisi',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='RFI Başlık'),
        ),
    ]
