# Generated by Django 4.2.13 on 2025-03-18 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('site_info', '0098_historicalrfi_sablonlar_rfi_kategorisi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrfi_kontrol',
            name='kontrol_ekleyen',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Onaylayan'),
        ),
        migrations.AddField(
            model_name='historicalrfi_kontrol',
            name='notlar',
            field=models.TextField(blank=True, null=True, verbose_name='Notlar'),
        ),
        migrations.AddField(
            model_name='rfi_kontrol',
            name='kontrol_ekleyen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kontrol_ekleyen', to=settings.AUTH_USER_MODEL, verbose_name='Onaylayan'),
        ),
        migrations.AddField(
            model_name='rfi_kontrol',
            name='notlar',
            field=models.TextField(blank=True, null=True, verbose_name='Notlar'),
        ),
    ]
