# Generated by Django 4.2.13 on 2025-03-31 15:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('site_info', '0100_historicalrfi_kontrol_red_sebebi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='rapor_bilgisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rapor_basligi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Rapor Başlığı')),
                ('rapor_aciklama', models.TextField(blank=True, null=True, verbose_name='Rapor Açıklama')),
                ('rapor_icerigi', models.TextField(blank=True, null=True, verbose_name='Rapor İçerik')),
                ('olusturma_tarihi', models.DateTimeField(null=True)),
                ('rapor_dosyalari', models.FileField(blank=True, null=True, upload_to='rapor_dosyalari/', verbose_name='Rapor Dosyası')),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('silinme_bilgisi', models.BooleanField(default=False)),
                ('olusturan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapor_olusturan', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('rapor_kime_ait', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Proje Ait Olduğu')),
            ],
        ),
        migrations.CreateModel(
            name='Historicalrapor_bilgisi',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('rapor_basligi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Rapor Başlığı')),
                ('rapor_aciklama', models.TextField(blank=True, null=True, verbose_name='Rapor Açıklama')),
                ('rapor_icerigi', models.TextField(blank=True, null=True, verbose_name='Rapor İçerik')),
                ('olusturma_tarihi', models.DateTimeField(null=True)),
                ('rapor_dosyalari', models.TextField(blank=True, max_length=100, null=True, verbose_name='Rapor Dosyası')),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('silinme_bilgisi', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('olusturan', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('rapor_kime_ait', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Proje Ait Olduğu')),
            ],
            options={
                'verbose_name': 'historical rapor_bilgisi',
                'verbose_name_plural': 'historical rapor_bilgisis',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
