# Generated by Django 4.2.13 on 2025-03-31 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_info', '0101_rapor_bilgisi_historicalrapor_bilgisi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalrapor_bilgisi',
            old_name='olusturma_tarihi',
            new_name='baslangic_tarihi',
        ),
        migrations.RenameField(
            model_name='rapor_bilgisi',
            old_name='olusturma_tarihi',
            new_name='baslangic_tarihi',
        ),
        migrations.AddField(
            model_name='historicalrapor_bilgisi',
            name='bitis_tarihi',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='rapor_bilgisi',
            name='bitis_tarihi',
            field=models.DateTimeField(null=True),
        ),
    ]
