# Generated by Django 4.2.13 on 2025-05-21 11:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('site_info', '0102_rename_olusturma_tarihi_historicalrapor_bilgisi_baslangic_tarihi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historicalgant_aitlikleri',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('gant_adi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Gantt Adı')),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('silinme_bilgisi', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('gant_blok', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='site_info.bloglar', verbose_name='Gantt Blogu')),
                ('ganti_degistiren_kisi', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Gantt değiştiren kişi')),
                ('gantt_sahibii', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Gantt Sahibi')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical gant_aitlikleri',
                'verbose_name_plural': 'historical gant_aitlikleris',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='gant_aitlikleri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gant_adi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Gantt Adı')),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('silinme_bilgisi', models.BooleanField(default=False)),
                ('gant_blok', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_info.bloglar', verbose_name='Gantt Blogu')),
                ('ganti_degistiren_kisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ganti_degistiren_kisi_Aitlik', to=settings.AUTH_USER_MODEL, verbose_name='Gantt değiştiren kişi')),
                ('gantt_sahibii', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gantt_sahibii_Aitlik', to=settings.AUTH_USER_MODEL, verbose_name='Gantt Sahibi')),
            ],
        ),
        migrations.AddField(
            model_name='gantt_olayi',
            name='gatn_aitlik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_info.gant_aitlikleri', verbose_name='Gantt Aitliği'),
        ),
        migrations.AddField(
            model_name='historicalgantt_olayi',
            name='gatn_aitlik',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='site_info.gant_aitlikleri', verbose_name='Gantt Aitliği'),
        ),
    ]
