# Generated by Django 4.2.13 on 2025-05-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_info', '0103_historicalgant_aitlikleri_gant_aitlikleri_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gant_aitlikleri',
            name='aciklama',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='historicalgant_aitlikleri',
            name='aciklama',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
    ]
