# Generated by Django 4.2.13 on 2025-11-11 22:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('site_info', '0104_gant_aitlikleri_aciklama_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='santiye_kalemleri_blok_verileri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metraj', models.FloatField(default=0, verbose_name='Metraj Bilgisi')),
                ('tutari', models.FloatField(default=0, verbose_name='Tutarı Bilgisi')),
                ('blok_agirligi', models.FloatField(default=0, verbose_name='Kalem Şantiye Ağırlığı')),
                ('blok_finansal_agirligi', models.FloatField(default=0, verbose_name='Kalem Finansal Ağırlık')),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('blog_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_info.bloglar', verbose_name='Blog Ait Olduğu')),
                ('kalem_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_info.santiye_kalemleri', verbose_name='Kalem Ait Olduğu')),
                ('proje_ait_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Proje Ait Olduğu')),
                ('proje_santiye_Ait', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_info.santiye', verbose_name='santiye Ait Olduğu')),
            ],
        ),
        migrations.CreateModel(
            name='Historicalsantiye_kalemleri_blok_verileri',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('metraj', models.FloatField(default=0, verbose_name='Metraj Bilgisi')),
                ('tutari', models.FloatField(default=0, verbose_name='Tutarı Bilgisi')),
                ('blok_agirligi', models.FloatField(default=0, verbose_name='Kalem Şantiye Ağırlığı')),
                ('blok_finansal_agirligi', models.FloatField(default=0, verbose_name='Kalem Finansal Ağırlık')),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('blog_bilgisi', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='site_info.bloglar', verbose_name='Blog Ait Olduğu')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('kalem_bilgisi', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='site_info.santiye_kalemleri', verbose_name='Kalem Ait Olduğu')),
                ('proje_ait_bilgisi', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Proje Ait Olduğu')),
                ('proje_santiye_Ait', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='site_info.santiye', verbose_name='santiye Ait Olduğu')),
            ],
            options={
                'verbose_name': 'historical santiye_kalemleri_blok_verileri',
                'verbose_name_plural': 'historical santiye_kalemleri_blok_verileris',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
