# Generated by Django 4.2.13 on 2025-11-22 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_info', '0105_santiye_kalemleri_blok_verileri_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genel_imalat',
            name='imalat_calisan_sayisi',
            field=models.FloatField(blank=True, null=True, verbose_name='İmalat Çalışan Sayısı'),
        ),
        migrations.AddField(
            model_name='genel_rapor',
            name='blok_bilgisi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_info.bloglar', verbose_name='santiye Ait Olduğu'),
        ),
        migrations.AddField(
            model_name='historicalgenel_imalat',
            name='imalat_calisan_sayisi',
            field=models.FloatField(blank=True, null=True, verbose_name='İmalat Çalışan Sayısı'),
        ),
        migrations.AddField(
            model_name='historicalgenel_rapor',
            name='blok_bilgisi',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='site_info.bloglar', verbose_name='santiye Ait Olduğu'),
        ),
    ]
