BBBBBBB BBBBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBBBBBBB
BBBB BBBBBB
BBBBB BBBB
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXX XXXXXX XXXX XXXXXX XXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXX XXXXXXXXX XXX XXX
    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXX XXXXX XXX XXX
    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXX XXX XXXXXX
    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXX XXXXXX XXXXXX
    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXXXXXXX XXXXXX XXXX XXXXXX XXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXXXXX
    XXXXXXXX XXXXXXXXXXXXX XX
    XXXXXXXXXXXXXXX
    XXXXXXXXXXXX
    XXXXXXXXXXXXXX

X
XXXXXXXX
XXXXXXXXX XXXXXX XXXX XXXXXX XXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
    XXXXXXX XXXXXBBBBBB BBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXX XXX XXX
    XXXXX XXXXXXBBBBBB BBXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXX XXXXX XXX XXX
    XXXXX XXXXXXBBBBBB BBXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXX XXX XXXXXX
    XXXXX XXXXXXBBBBBB BBXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXX XXXXXX XXXXXX
    XXXXX XXXXXXBBBBBB BBXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXBBBBBB BBXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXXXXXXX XXXXXX XXXX XXXXXX XXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    BBBBBBBB BBBB
BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    BBBBBBBBBB

            XXXX XXXXXXXXXXXXXXXXXXXXXXXX

                XXXX XXXXX XXXX XXXXX XXX
                XXXX XXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                            XXX XXXXXXXXXXXXXXXX gettext(u'Satış Ekle') XXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                                XXX XXXXXXXXXXXXXXXXX XXXXX
                                    XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX gettext(u'Dashboard') XXXXXXXXX
                                    XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX gettext(u'Satış Ekle') XXXXX
                                XXXXX
                            XXXXXX
                        XXXXXX
                 
                XXXX XXX XXXX XXXXX XXX

                XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXX
XXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXX gettext(u'Genel Bilgiler') XXXXX
    XXXX XXXXXXXXXXXXXXXX
        XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXX gettext(u'Vazgeç')  
        XXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXX gettext(u'Kaydet')  
        XXXXXXXXX
    XXXXXX
XXXXXX
XXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXX XXXXX
        XXXX XXXX XXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXXXXX gettext(u'Kayıtlı cariler için cari adının ilk üç karekterini giriniz.') X XXXXXXXXXXXXX gettext(u'Cari Hesabı') X XXXXXXXXXXXXXXXXXXX
            XXXXXX
        XXXXXX

        XXXX XXXXXXXXX XX XXXX XXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX
                XXXXXXX gettext(u'Düzenleme ve Vade Tarihi') XXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXBBBBBBBBBXX
            XXXXXX
        XXXXXX

        XXXX XXXXX XXXX XX XXXXXX XXX XXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXX
                        XXXXXXX gettext(u'Döviz Kuru (Sadece IQD)') XXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX 
                                XXXXXXXXXXXXX gettext(u'Örn: 1450 veya 1450.06') X 
                                XXXXXXXXXXXXXXXXXXXXXXXXX 
                                XXXXXXX gettext(u'Lütfen sadece sayısal değer giriniz') X 
                                XXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'IQD') XXXXXXX
                        XXXXXX
                    XXXXXX
                XXXXXX

                XXXX XXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXX
                        XXXXXXX gettext(u'Toplam IQD') XXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'IQD') XXXXXXX
                        XXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX

        XXXX XXXXXX XX XXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX
                XXXXXXX gettext(u'Fatura No') XXXXXXXX
                BB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
                BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBB
                BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                     XXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXX XX
                XXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XX                                                   
                BBBB
                                                                                
                BBBBB
                BBBB
                       XXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBX XXXXXXXX XX
                XXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBX XX                                                 
                BBBBB
                
            XXXXXX
        XXXXXX

        XXXX XXXXXXXX XXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX
                XXXXXXX gettext(u'Açıklama') XXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Açıklama') XX
            XXXXXX
        XXXXXX

        XXXX XXXXXXXX XX XXXXXX XXXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX
                XXXXXXX gettext(u'Kategori') XXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                        BBB B BB BBBBBBBBBBBBBBBBB
                        XXXXXXX XXXXXXXXXXXXXXXXXX
                        BBBBBB
                    XXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX gettext(u'Gelir Kategorisi Ekle') 
                    XXXXXXXXX
                XXXXXX
            XXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX XXXXXXXX
                XXXXXXX gettext(u'Etiketler') XXXXXXXX
                XXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXXXX
                        BBB B BB BBBBBBBBBBBBB
                        XXXXXXX XXXXXXXXXXXXXXXXXX
                        BBBBBB
                    XXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX gettext(u'Etiketi Ekle') 
                    XXXXXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXX
                        XXXXXXX gettext(u'Belge Yükle') XXXXXXXX
                        XXXXXX XXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XX
                    XXXXXX
                XXXXXX
    XXXXXX
XXXXXX

XXXX XXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX gettext(u'Fatura Kalemleri') XXXXXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXX gettext(u'HİZMET / ÜRÜN') XXXXX
        XXX XXXXXXXXXXXXXXX gettext(u'MİKTAR') XXXXX
        XXX XXXXXXXXXXXXXXX gettext(u'BİRİM FİYAT') XXXXX
        XXX XXXXXXXXXXXXXXX gettext(u'TOPLAM') XXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXX XXXXXXXXXX X
            XXXX XXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Ürün / Hizmet Adı') X XX
                XXXXXX
                XXXX XXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
                XXXXXX
                XXXX XXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
                    XXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXX
                    XXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Açıklama Ekle') XXXXX
                        XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'İndirim Ekle') XXXXX
                    XXXXX
                    XXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'İndirim gir %%') XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Açıklama Giriniz') XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX
        XXXXXX gettext(u'Yeni Satır Ekle') XXXXXXX
    XXXXXX
XXXXXX

XXXX XXXXXXXXXXX XXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXX XXXXXX
            XXXX XXXXXXXXXX XXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXX gettext(u'ARA TOPLAM') XXXXX
                XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXX XXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXX gettext(u'ÖDENECEK TUTAR') XXXXX
                XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX


                XXXXXX
                XXXXXXX XXXXXX
            XXXXXX
        XXXXXX
        XXXXXXX XXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X 
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXX
                        XXXX  XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXX

                        XXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXXXXX
    XXXXXX
    XXXX XXX XXXX XXXXXXXXXX
XXXXXXX
XXXX XXXXXXXXXX XXX

XXXXXXX XXXXXBBBBBB BBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXBBBBBB BBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXBBBBBB BBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXBBBBBB BBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXBBBBBB BBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXBBBBBB BBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXX XXXXX XXXXXX XX XXX
XXXXXXX XXXXXBBBBBB BBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXX XXX XX XXX
XXXXXXX XXXXXBBBBBB BBXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXX XXXXXX XXXX XXXXXXXXXXX
XXXXXXXX
    XXXXXXXXXX XX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXX
        XX XXXXXXXX XXXXXXX XXXX XXXXXX X
            XXXXXXXXXXXXX gettext(u'A new date selection was made:')  X X XXXXXXXXXXXXXXXXXXXXXXXXXX X X XX X X XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX
    XXX
XXXXXXXXX
XXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
    XX XXXXX XXXX XXXXXX XXXXXXXX
    XXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXX X XXX 
    XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXX

    XX XXXXX XXXX XXXXXXX XXXXX XXXXXX XXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
        XXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXX
    XXX

    XX XXXXX XXXXX XXXXX XXXXXXXXXXXX XXXXXX XXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXX
    XXX

    XX XXXXX XXXXX XXXXX XXXXXXXXXXXX XXXXXX XXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXX
    XXX
XXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
    XXXXXXXX XXXXXXXXXXXXXXXXXX X
        XXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX
        XXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XX XX

        XX XXXXXXXXXX XX XXXXXXXXXXXXXX X
            XXX XXXXXXXXX X XXXXXXXXXXXXX X XXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXX
        X
    X

    XX XXXXX XXXX XXXXXXXXXX XXXXXXXXX XXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX

    XX XXXX XXXXXXX XXXX XXXXXX XXXXXXXXXXXX XXXXXXXXX XXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
            XX XXXX XXX XXXXXXX XX XXXXXXXX XXXXXX XXXXXXXXXXX
            XXXXXXXXXXXXXXX
            XX XXXXXXXX XXX XXXXXXXX XXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXX
        XXX
    XXX

    XX XXX XXXXXXXXX XXXXXXXXX XXX
    XXXXXXXXXXXXXXXXXXX
XXX

XXXXXXXX XXXXXXXXXXXXXX X
    XXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXX X XX

    XXX XXXX X X XX X X XXXXXXXXXXXXXXXXX XXXX X
        XXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    X

    XXX XXXXXXXXXXXX X XX
    XXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXX X X XX X X XXXXXXXXXXXXXXXXXX XXXX X
        XXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    X

    XXX XXXX X X XX X X XXXXXXXXXXXXXXX XXXX X
        XXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    X

    XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXX X X XXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXX X X XXX
X


XXXXXXXX XXXXXXXXXXXXXXXXXX X
    XXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX
    XXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX
    XXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX

    XX XXXXXXX XXXXXX XXXXXX
    XX XXXXXXXXXX XX XXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXX
    X

    XX XXXXXXX XXXXXX XXXXXX
    XX XXXXXXXXXX XX XXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXX
    X
X

XXX XXXXXXXXXXXXXX X XXXXXX  XX XXXXXXXX XXXXXXX XXXX XXXXXXXXXX XXXXX XXXXX XXXX

XXXXXXXX XXXXXXXXXXXXXXXXXXX X
    XXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXX

    XX XXXXXX XXXXXXX XXXXX XX XXXXXXX XXXX XXXXXXXX XXXXX XXXX XXXX XXXXXXXX
    XXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXX

    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XX XXXX XXXXXX XXX XXXXX XXXXXXXXXXXX XXXX XXX XXXXX XXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX gettext(u'Geçersiz Döviz Kuru') XX X gettext(u'Lütfen geçerli bir döviz kuru giriniz. Sadece sayısal değer ve ondalık olabilir.') XXX
        X

        XXXXXXXXXXXXXXXXXXXX X XXX  XX XXXXXXX XXXXXXX XXXXXX XXXXXXX
    X
X

XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX X
    XXXXXXXXXXXXXX X XXXXX  XX XXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXX

    XXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXX
    
    XXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXX
    
    XXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXX X XXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    
    XXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXX
    
    XXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXX X XXXXXX
    
    XXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX
    
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    
    XXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXX
    
    XXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXX X XXXXXX  XX XXXXX XXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXXXX
        XX XXXXX
    XX XXXXXX
X


XXXXXXXXX


XXXX XXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXX XXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX XXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
    XXXXXX
    XXXX   XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXX XXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXX XXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
XXXXXX
XXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXX
                                XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXX

                                XXXX XXXXXXXXXXXXXXXXXXX
                                    XXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXX
                                    XXXX XXXXXXXXXXXXX
                                        XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Gider Kategorisi Adı') XXXXXXXX
                                        XXXXXX XXXXXXXXXXX  XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Kategori Adı') X XX
                                    XXXXXX
                                    XXXX XXXXXXXXXXXXX
                                        XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Gider Kategorisi Açıklaması') XXXXXXXX
                                        XXXXXX XXXXXXXXXXX  XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Kategori Açıklaması') X XX
                                    XXXXXX
                                    XXXX XXXXXXXXXXXXX
                                        XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Gider Kategorisi Rengi') XXXXXXXX
                                        XXXXXX XXXXXXXXXXXX  XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Gider Rengi') X XX
                                    XXXXXX
                                XXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXXXX
                                    XXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXX
                                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Kapat') XXXXXXXXX
                                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX gettext(u'Kategori Ekle') XXXXXXXXX
                                        XXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
                                    XXXXXX
                                XXXXXX
                        XXXXXX
                    XXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXX
                                XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXX

                                XXXX XXXXXXXXXXXXXXXXXXX
                                    XXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXX
                                    XXXX XXXXXXXXXXXXX
                                        XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Gider Etiketi Adı') XXXXXXXX
                                        XXXXXX XXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Etiket Adı') X XX
                                    XXXXXX

                                XXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXXXX
                                    XXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXX
                                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Kapat') XXXXXXXXX
                                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Etiketi Ekle') XXXXXXXXX
                                        XXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
                                    XXXXXX
                                XXXXXX
                        XXXXXX
                    XXXXXX
                XXXXXX
BBBBBBBB BBBBBBB
BBBBB BBBBBBBBBBBBBBBBB


XXXXXXXXX XXXXXX XXXX XXXXXXXXXXX
XXXXXXXX

      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXX
      XX XXXXXXXXXXXXXXX XXXX XXXXXX X
        XXXXXXXXXXXXXX XXX XXXX XXXXXXXXX XXX XXXXX X X XXXXXXXXXXXXXXXXXXXXXXXXXX X X XX X X XXXXXXXXXXXXXXXXXXXXXXXXXX
      XXX

XXXXXXXXX
XXXXXXX
XXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXX XXXXXX
    XXXX XXXX
    XXXXX XXXX
    XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
    XXXXXXXX XXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXXXX XXXXXXX
    XXXXXXXX XX
    XXXXXXXXXXX XXXXXXX XXXX XXXXX XXXXXXXXX XXXX XXXXX
    XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
X

XXXXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXX XX
    XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
X

XXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXX XXXXXXXX
    XXXXXX XXXXXXXX
    XXXXXXXX XXXX XXXXX
    XXXXXXXXXXXXXX XXXX
    XXXXXXXXXXX X XXX XXXX XXXXXXX XX XX XXXXX
    XXXXXXXXXX XXXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXXX XXXXXXX
X

XXXXXXXXXXXXXXXXXX X
    XXXXXXXXXX XXXXX
    XXXXXXXXXXXXX XXXXX
    XXXXXX XXXXXXXX XX XXXX XXXXX XX
X

XXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXX XXXXX
    XXXXXXXXXXXXXXX XXXXXXX
X

XXXXXXXXXXXXXXXXXXXXX XXXXXX X
    XXXXXXXXXX XXXXX
    XXXXXXXXXXXXXX XXXX
X

XXXXXXXXXXXXXXXXXXXXX X X
    XXXXXXX XX
    XXXXXXXXXX XXXXX
    XXXXXX XXXXXXXX XX XXXX XXX XXXXX XXXXX XX
X

    XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXX
        XXXXXX XXXXXX
    X
    XXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXX  XXXXXX XXXXXXXXXXX
    XXXXXXXXXX XXXXX XXXXXXXXXXX
    XXXXXXXX XXX XXXXXXXXXXX
    XXXXXXXXXX XXXX XXXXXXXXXXX
    XXXXXXXXXXX XXXXX XXXXXX XXXXXX
    X
    XXXXXXXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
         XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX


BB BBBBBBBBBB
                                                    

    XXXXXXXX

       XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX
        XXX XXXXXXXXXXXXXX X XX

        XXX XXXX X X XX X X XXXXXXXXXXXXXXXXX XXXX X
            XXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X

        XXX XXXXXXXXXXXX X XX
        XXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXX X X XX X X XXXXXXXXXXXXXXXXXX XXXX X
            XXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X

        XXX XXXX X X XX X X XXXXXXXXXXXXXXX XXXX X
            XXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X

        XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXX X X XXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXX XXXXXXXXXXXX X X XXX
    X

    XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBXX
        XXXXXXXXXX XX
        XXXXXXX XXXXXXXXXXXXXXX XXX X
            XXX XX X XXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX X XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXX
        X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXX XXXXX X
        XXXXXX XXXXXXXXX
            XXXXXXXXXXXXXXX X XXXXXXXXXX X X  X X XXXXXXXXXX X X XXXXXXXXXXX
            XXXXXXXXXXXXXX
    XX
X

XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXX X
        XXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX


    XX XXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXX
XXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBXX
                XXXXXXXXXX XX
                XXXXXXX XXXXXXXXXXXXXXX XXX X
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXX XXXX XXXXX XXXXX XXXXXXX XXXXXXX

                    XXXXXX XXXXXX
                X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXX XXXXX X
                XXXXXX XXXXXXXXX
                    XXXXXXXXXXXXXXX X XXXXXXXXXX X XXXXXX X XXXXXXXXXX X XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXX XXX XX XXXXX XXXXXX
                    XXXXXXXXXXXXXX
            XX
        XXX

XX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXX XX
                XXXXXXX XXXXXXXXXXXXXXX XXX X
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXX XXXX XXXXX XXXXX XXXXXXX XXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXX XXXXXX XXXXX XXXXXXXX XXXXXXXX XXXXXX XXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXX XXXXX XXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXX
                    XXXXXX XXXXXX
                X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXX XXXXX X
                XXXXXX XXXXXXXXX
                    XXXXXXXXXXXXXXX X XXXXXXXXXX X XXXXXX X XXXXXXXXXX X X XXXXXXXXXXX XX XXXXXXXX XXXXXXXXXXXX XXXXX XXX XX XXXXX XXXXXX
                    XXXXXXXXXXXXXX
            XX
        XXX
    XXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        XX XXXXX XXXXX XXXXXXX XXXXX XXXXXXXXXXXXX XX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XX XXXXXXXXX XXXX XXXXX XXX XXXXX XXXXXXX XXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX
XXX
XX
       XXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX
        XXX XXXXXXXXXXXXXX X XX

        XXX XXXX X X XX X X XXXXXXXXXXXXXXXXX XXXX X
            XXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X

        XXX XXXXXXXXXXXX X XX
        XXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXX X X XX X X XXXXXXXXXXXXXXXXXX XXXX X
            XXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X

        XXX XXXX X X XX X X XXXXXXXXXXXXXXX XXXX X
            XXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X

        XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXX X X XXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXX XXXXXXXXXXXX X X XXX
    X

    XXXXXXXXX
XXXXXXX
  XXXXXXXXXXXX
    XXXXXXXXXX XXXX XXXXXXXXXXX
  X
XXXXXXXX
XXXXXXXX

    XX XXXXXXXX XX XXXXXXXXXX XXXXXXXXXXXXXX
    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXX XXXXX
            XXXXXXX XXXXX
            XXXXXXXXXXXX X gettext(u'Search') XX
            XXXXXXXXX X
                XXXXXXXXXX XXXXXXXXXX
                XXXXXXXXXXXX XXXXXXXXXX
                XXXXXXXX XXXXXXXXXX
            XX
            XXXXXXXXX XXXXXXXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXXX
            X
        XXX
    X
XXX XXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXX


    XXXXXXXXXXXXXXXXXXXXXXXXXX XX X
        XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX X
            XXX XXX X XXXXXXXXXXXXXXXX
                XXX X XXXXXXXXXXXXXXXX
                XXXXXXXX X XXXXXXXXXXXXXXXXXXXXX
                XXXX X XXXXXXXXXXXXXXXXX

            XXXXXXXX
                XXXXX XXXXXXX
                XXXX XXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
                XXXXX X
                    XXXX XXXX
                    XXXX XXXX
                    XXXXXXXXX XXXXXXXXX
                    XXXXX XXXXX
                    XXXXXXXXXXXXXXXXXXXX XX
                XX
                XXXXXXXX XXXXXXXX XXXXXX X
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X X XXXXXXXXXXXX
                X
            XXX
            XXXXXX XXXXXX
        XXX
    XXX
    XXXXXXXXXXXXXXXXXXXXXXXXXX XX X
  XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX X
    XXXX X XXXXXXXXXXXXXXXXX
    XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXXX
      XXXXX XXXXXXX
      XXXX XXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
      XXXXX X
        XXXXX XXXXX
        XXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XX
      XX
      XXXXXXXX XXXXXXXX XXXXXX X

        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X X XXXXXXXXX XXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXX XXX

      X
    XXX
    XXXXXX XXXXXX XXXXXXX XXXX XX XXXX
  XXX
XXX

XXXXXXXXX
BBBB
                                                     

    XXXXXXXX

       XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX
        XXX XXXXXXXXXXXXXX X XX

        XXX XXXX X X XX X X XXXXXXXXXXXXXXXXX XXXX X
            XXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X

        XXX XXXXXXXXXXXX X XX
        XXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXX X X XX X X XXXXXXXXXXXXXXXXXX XXXX X
            XXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X

        XXX XXXX X X XX X X XXXXXXXXXXXXXXX XXXX X
            XXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X

        XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXX X X XXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXX XXXXXXXXXXXX X X XXX
    X

    XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXX XX
        XXXXXXX XXXXXXXXXXXXXXX XXX X
            XXX XX X XXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX X XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXX
        X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXX XXXXX X
        XXXXXX XXXXXXXXX
            XXXXXXXXXXXXXXX X XXXXXXXXXX X X  X X XXXXXXXXXX X X XXXXXXXXXXX
            XXXXXXXXXXXXXX
    XX
X

XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXX X
        XXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX


    XX XXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXX
XXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXX XX
                XXXXXXX XXXXXXXXXXXXXXX XXX X
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXX XXXX XXXXX XXXXX XXXXXXX XXXXXXX

                    XXXXXX XXXXXX
                X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXX XXXXX X
                XXXXXX XXXXXXXXX
                    XXXXXXXXXXXXXXX X XXXXXXXXXX X XXXXXX X XXXXXXXXXX X XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXX XXX XX XXXXX XXXXXX
                    XXXXXXXXXXXXXX
            XX
        XXX

XX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXX XX
                XXXXXXX XXXXXXXXXXXXXXX XXX X
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXX XXXX XXXXX XXXXX XXXXXXX XXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXX XXXXXX XXXXX XXXXXXXX XXXXXXXX XXXXXX XXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXX XXXXX XXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXX
                    XXXXXX XXXXXX
                X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXX XXXXX X
                XXXXXX XXXXXXXXX
                    XXXXXXXXXXXXXXX X XXXXXXXXXX X XXXXXX X XXXXXXXXXX X X XXXXXXXXXXX XX XXXXXXXX XXXXXXXXXXXX XXXXX XXX XX XXXXX XXXXXX
                    XXXXXXXXXXXXXX
            XX
        XXX
    XXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        XX XXXXX XXXXX XXXXXXX XXXXX XXXXXXXXXXXXX XX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XX XXXXXXXXX XXXX XXXXX XXX XXXXX XXXXXXX XXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX
XXX
XX
       XXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX
        XXX XXXXXXXXXXXXXX X XX

        XXX XXXX X X XX X X XXXXXXXXXXXXXXXXX XXXX X
            XXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X

        XXX XXXXXXXXXXXX X XX
        XXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXX X X XX X X XXXXXXXXXXXXXXXXXX XXXX X
            XXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X

        XXX XXXX X X XX X X XXXXXXXXXXXXXXX XXXX X
            XXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X

        XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXX X X XXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXX XXXXXXXXXXXX X X XXX
    X

    XXXXXXXXX
XXXXXXX
  XXXXXXXXXXXX
    XXXXXXXXXX XXXX XXXXXXXXXXX
  X
XXXXXXXX
XXXXXXXX

    XX XXXXXXXX XX XXXXXXXXXX XXXXXXXXXXXXXX
    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXX XXXXX
            XXXXXXX XXXXX
            XXXXXXXXXXXX X gettext(u'Search') XX
            XXXXXXXXX X
                XXXXXXXXXX XXXXXXXXXX
                XXXXXXXXXXXX XXXXXXXXXX
                XXXXXXXX XXXXXXXXXX
            XX
            XXXXXXXXX XXXXXXXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXXX
            X
        XXX
    X
XXX XXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXX


    XXXXXXXXXXXXXXXXXXXXXXXXXX XX X
        XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX X
            XXX XXX X XXXXXXXXXXXXXXXX
                XXX X XXXXXXXXXXXXXXXX
                XXXXXXXX X XXXXXXXXXXXXXXXXXXXXX
                XXXX X XXXXXXXXXXXXXXXXX

            XXXXXXXX
                XXXXX XXXXXXX
                XXXX XXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
                XXXXX X
                    XXXX XXXX
                    XXXX XXXX
                    XXXXXXXXX XXXXXXXXX
                    XXXXX XXXXX
                    XXXXXXXXXXXXXXXXXXXX XX
                XX
                XXXXXXXX XXXXXXXX XXXXXX X
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X X XXXXXXXXXXXX
                X
            XXX
            XXXXXX XXXXXX
        XXX
    XXX
    XXXXXXXXXXXXXXXXXXXXXXXXXX XX X
  XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX X
    XXXX X XXXXXXXXXXXXXXXXX
    XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXXX
      XXXXX XXXXXXX
      XXXX XXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
      XXXXX X
        XXXXX XXXXX
        XXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XX
      XX
      XXXXXXXX XXXXXXXX XXXXXX X

        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X X XXXXXXXXX XXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXX XXX

      X
    XXX
    XXXXXX XXXXXX XXXXXXX XXXX XX XXXX
  XXX
XXX

XXXXXXXXX
BBBBB


BBBBBBBB BBBBBBBBBBBBBBBBB