    XXXXXXX
        XX XXXXX XXXXXX XX
XXXXXX X
    XXXXXXXX XXXXX
    XXXXXXXXX XXXXXX
    XXXXXXXX XX
    XXXXX XX
    XXXX XX
    XXXXXX XXXXX
    XXXXXXX XXXXX
    XXXXXXXXX XXXXX
    XXXXXXXXXXXXXXXXX XXXXXXX XX XX XXXXX
X

XXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXX XXXXXX
    XXXXXXX XXX XXXXX
    XXXXXXXX XXXXX
    XXXXXXX XXX XXXXX XXXXX
    XXXXXX XXXXXX
    XXXXXXXXXXXXXX XXXX
X

XXXXXXXXXXXXX X
    XXXXXX XXXXX
    XXXXXX XXXXXX
    XXXXXXXXXX XXXXX
    XXXXXXXXXXXX XXXXX
X

XXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXX X
    XXXXXX XXXXXX
    XXXXXXXXXXXXXXXX XXXXX
    XXXXXXX XXXXXXXX
X

XXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXX
X

XXXXXXXX X
    XXXXXX XXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXXXX XXXXX
    XXXXXXXXXXX XXXXXX
X

XXXXXXXX XXXXXX X
    XXXXXX XXXX
    XXXXXXXX XXXXX
    XXXXXXX XXXX
    XXXXXXXXXX XXXXX
    XXXXXXX XXXXX
    XXXXXXXXXXXXXXXXX XXXXXXXX
    XXXXXXX XXXXXXXX
    XXXXXXXXXXXXXX XXXX
X

XXXXXXXX XXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXX XXXXXXXX
X

    XXXXXXXX
    XXXX XXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX
                XXXX XXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXXXX
   XX XXXXXX XXXXXX XXXXXX
XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XX XXXXXX XXXXXX
XXXXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XX XXXXXXX XXXXXXXXX XXXXXX
XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XX XXXXXX XXXXXXXXXX XXXXXX XX
XXXXXXXXXXX X XXXXXXXXXX X
    XXXXXXXXXXXXXXXXXXX X XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
X

XX XXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXX XXXXX
XXXXXXXXXXXXXXXX X XXXXXXXXXX X
    XXXXXXXXXXXXXXXXXXX X XXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
X

XX XXXXX XXXXXX XXXXXXXXXX XXXXXX XXXXX
XXXXXXXXXXXXXX X XXXXXXXXXXXXXXX X
    XX XXXXXXXXXXXXX XXX XXXXXX X
        XXXXXXXXXXXXXXXXXXX X XXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    X
X

XX XXXXX XXXXXXXX XXXXXXXXXXXXX
XXXXXXXX XXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXX
X

XXXXXXXX XXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXX
X

XXXXXXXX XXXXXXXXXXX X
    XXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    X XXXXX XXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX
    X
X

XX XXXXXX XXXXXXXXXX XXXXXX
XXXXXXXX XXXXXXXXXXXXXXXXXXXXX X
    XXXXX XXX X XXXXXXXXXX
    XX XXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXX
    X XXXX XX XXXX XXX XXX XX XXX XXX XXX XX XXX XXX XXX XX XXX XXX XXXX X
        XXXXXXXXXXXXXXXXXX
    X XXXX XX XXXX XXX XXXXXXXX X
        XXXXXXXXXXXX
    X XXXX XX XXXX XXX XXXXXXXXX X
        XXXXXXXXXXXXXXX
    X XXXX XX XXXX XXX XXXXXXXXXXXX X
        XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXX XXXX
    X
X


XXXXXXXXX