XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXX
    XXXXXXX
        XXXX X
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXX XXXXXXX
          
            XXXXXXX XX
            XXXXXXXXXXXXXXXXX XXXXXXXX
        X

        XXXXXXXXXXXXXXXXXXX X
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXX XXXXXXX
            XXXXXXXXX XXXXXXX XX XXXXXX XXXXXXXX XXXX XXXXXXX XX
            XXXXXX XXXXX
            XXXXXXX XXXXX
        X

        XXXXXXXXX X
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
            XXXXXXX XXXXX
            XXXXXX XXXXXX
            XXXXXXXXXXXXXXXXX XXX XXXXXXX XX XXX XXXXXXX XXXX XXXXXXXXX XXXXX XX
            XXXXXXXXXX XXXXXXXXX XX XXXXXXX XXXXX XX
            XXXXXXXXXXX XXXXXXXXX XXXX XXXXX XX XXXXXXXXXXXX XXXXXXX XXXXXX XX
        X

        XXXXXX X
            XXXXXXXXX XXXXXXXXX
            XXXXXXXXXXX XXXXXX XX XXXXXXX XXXXXX XX
            XXXXXXX XXXXXXXX
        X

        XXXXXX XXX X
            XXXXXX XXXXX
            XXXXXXX XXXXX
            XXXXXXXXXXX XXXXXX XXXX XXXXX XX XXXX XXXXXXXXXXX XXXXXX XX
        X

        XX XXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXX XXXX XX
        XXXXXX XXXXXXXXX X
            XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XX XXXXX XXXXXX XXXXXXXXXX XX
        X

        XX XXXXXXXXX XX
        XXXXXXXXXX XXXXXXXXXXX X
            XX X XXXXXXX XXXXX X
            XXX X XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX  X XX XXXX XXXX XX
            XXXX X XXXXXXX XXXXX X X
        X

        XXXXXXXXXXXXXX X
            XXXXXXXXXX XXXXXXXXXXX XX XXXXXXXXX XX X XXXXXX XXXXX XX XXXXXX XXXXXX XXXX XXXXXXXXX XX
        X

        XXXXXXXXXXXX X
            XXXXXXXXX XXXXXXXXX
            XXXX XXXX
            XXXXX XXXX
            XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
            XXXXXX XXXXX
            XXXXXXXXXXXX XXXXX
            XXXXXXXXXXXX XXX XXX XXX XXXXXXX XX XX XXXXX
        X

        XX XXXXX XXXXXX XX
        XXXXXX X
            XXXXXXXX XXXXX
            XXXXXXXXX XXXXXX
            XXXXXXXX XXXXX XX XXXXXXX XXXXX XX XXXXXX XX XXX XX
            XXXXX XX
            XXXX XX
            XXXXXX XXXXX
            XXXXXXX XXXXX
            XXXXXXXXX XXXXX
            XXXXXXXXXXXXXXXXX XXXXXXXXXXX
            XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
            XXXXXXXXXXXX XXXXX
        X

        XXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXX XX XXXXX
            XXXXXXXX XXXXX
            XXXXXXX XXX XXXXX XXXXX
            XXXXXX XXXX
        X

        XXXXXX X
            XXXXXX XXXXX
            XXXXXX XXXXXX
            XXXXXXXXXX XXXXX
            XXXXXXXXXXXX XXXXX
        X

        XXXXXXXXXXXXX
        XXXXXXXXXXXX X
            XXXXXX XXXXXX
            XXXXXXXXXXXXXXXX XXXXX
            XXXXXXX XXXXXXXX
        X
    XXXXXXXX
XXXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
XXXXXX

XXXX XXXXX XXXXXXXX XXX
XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXXXXX XXXX XX XXX XXXXXXXXXXX
    XXXXXX
XXXXXX

XXXXXXXX
    XX XXXXXXXX XX XXX XXXXXX XXXX XXXXXX
    XXXXXXXX XXXXXXXXXXXXXXXXXXXXX X
        XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXX X XXX  XX XXXXX XXXXXXXX XXXXXX

        XXX XXXX X X XX X XX XXXXXXXXXXX XXXX X
            XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXX X XXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXX X XX

            XX XXX XXXXXXX XXXXX XX XXX XXXXX XXXXXX
            XXXXXXXXXXXXXXXXXX X XXXXXXXXXX X XX XX XXXXX XXXXXX XXXX XXXX XXXXXX XXXXXXX

            XX XXX XXXXX XXX XXX XXXXX XXXX XXXX XXX XXXXX XXXXX
            XXXXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXX X XXXXXXXXXXXXXXXX XX XXXXXXX XXXX XXXX XXXXX XXX
            XXXXXXX X X X XX XXXXX
            XXXXXXXXXXXXXXXXXXXXXXX

            XX XXXXXXXXX XXX X XXXXX XX XXX XXXXX
            XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXX X XXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX X X X XX XXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXX

            XX XXX XXXXX XXXXX XX XXXX XXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
                XXXXXXXXXXXXX
            XXX

            XX XXX XXXXXXXXX XX XXX XXXXX XXXXX XXXX XXXXXXXX XXX XXX XXXXXX XXXX XX X XXXXXXXX XXXXX XX XXX XXXXXXXXXXXXXX
            XX XX XXX XXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            X

            XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X

        XX XXXXXX XXX XXXXX XX XXX XXX XXXXXX XXXXXX XXX XXXX
        XXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

        XX XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX X
            XXXXX XXXXX X XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXX
        X XXXX X
            XXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXX
        X
    X

    XX XXXXXXXX XX XXXX XXXXX
    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX X
        XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXX X XX XXXXX XXXXXXXXX XXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX X XXXXXXXX

        XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXX X XXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXX X XXXXXXX
        X

        XXXXXXXXXXXXXX X XXXXXXXXXXXXXXX X
            XX XXXXXXXXXXXXX XX XXXXXX X
                XXXXXXXXXXXXXXXXXXX X XXXXXXX
            X
        X
    X

    XX XXXXXXXXXX XXXX X XXXXXX
    XXXXXXXXXXXXXX
XX XXX XXXXX XXXXXXXXX XXX XXXXXXXX XXX XXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XX X
        XXXXXXXXXX X XXXXX
        XXXXXX X XXXXXXXXXX
    XXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XX X
        XX XXXXXXXXXXXX X
            XXXXX XX X XXXXXXXXX X XXXXXXX
            XXXXXXXX XX XX X XXXX XX XXXXXXXX XXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX X XXXXXXXXXX
        X
    XXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
        XXXXXXXXXX X XXXXXX
    XXX
XXXXXXXXX

XXXXXXX
XXXXXXX
