# Generated by Django 4.1.2 on 2023-12-13 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='cari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cari_adi', models.CharField(blank=True, max_length=400, null=True, verbose_name='Cari Adı')),
                ('telefon_numarasi', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon Numarası')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Cari Açkıklama')),
                ('bakiye', models.FloatField(default=0, verbose_name='Cari Bakiyesi')),
                ('silinme_bilgisi', models.BooleanField(default=False)),
                ('cari_kart_ait_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Cari Kartın Kime Ait Olduğu')),
            ],
        ),
    ]
