# Generated by Django 4.1.2 on 2023-12-13 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('muhasebe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kasa_adi', models.CharField(blank=True, max_length=400, null=True, verbose_name='Kasa Adı')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Kasa Açkıklama')),
                ('bakiye', models.FloatField(default=0, verbose_name='Kasa Bakiyesi')),
                ('silinme_bilgisi', models.BooleanField(default=False)),
                ('kasa_kart_ait_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kasa Kime Ait Olduğu')),
            ],
        ),
    ]
