# Generated by Django 4.1.2 on 2023-12-13 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('muhasebe', '0002_kasa'),
    ]

    operations = [
        migrations.CreateModel(
            name='gider_kategorisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gider_kategori_adi', models.CharField(blank=True, max_length=400, null=True, verbose_name='Gider Adı')),
                ('gider_kategorisi_renk', models.CharField(blank=True, max_length=200, null=True, verbose_name='Gider Kaqtegorisi Renk')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Gider Kategorisi Açkıklama')),
                ('silinme_bilgisi', models.BooleanField(default=False)),
                ('gider_kategoris_ait_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Gider Kategorisi Ait Olduğu')),
            ],
        ),
        migrations.CreateModel(
            name='gelir_kategorisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gelir_kategori_adi', models.CharField(blank=True, max_length=400, null=True, verbose_name='Gelir Adı')),
                ('gelir_kategorisi_renk', models.CharField(blank=True, max_length=200, null=True, verbose_name='Gelir Kaqtegorisi Renk')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Gelir Kategorisi Açkıklama')),
                ('silinme_bilgisi', models.BooleanField(default=False)),
                ('gelir_kategoris_ait_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Gelir Kategorisi Ait Olduğu')),
            ],
        ),
    ]
