# Generated by Django 4.1.2 on 2023-12-13 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('muhasebe', '0004_gider_etiketi_gelir_etiketi_gelir_bilgisi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gelir_bilgisi',
            name='gelir_kime_ait_oldugu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Gelir Kategorisi Ait Olduğu'),
        ),
        migrations.CreateModel(
            name='Gider_Bilgisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fatura_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Fatura Tarihi')),
                ('fatura_no', models.CharField(blank=True, max_length=200, null=True, verbose_name='Fatura No')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Gelir Açıklaması')),
                ('urun_adi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ürün Adı')),
                ('adet', models.FloatField(default=1, verbose_name='Ürün Adeti')),
                ('tutar', models.FloatField(default=0, verbose_name='Toplam Tutar')),
                ('cari_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='muhasebe.cari', verbose_name='Cari Bilgisi')),
                ('gider_etiketi_sec', models.ManyToManyField(blank=True, null=True, to='muhasebe.gider_etiketi')),
                ('gider_kategorisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='muhasebe.gider_kategorisi', verbose_name='Gider Kategori Bilgisi')),
                ('gider_kime_ait_oldugu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Gider Kategorisi Ait Olduğu')),
            ],
        ),
    ]
