# Generated by Django 4.1.2 on 2023-12-13 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('muhasebe', '0005_alter_gelir_bilgisi_gelir_kime_ait_oldugu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gelir_bilgisi',
            name='silinme_bilgisi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gider_bilgisi',
            name='silinme_bilgisi',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='virman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('virman_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Virman Tarihi')),
                ('tutar', models.FloatField(default=0, verbose_name='Toplam Tutar')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Virman Açıklaması')),
                ('silinme_bilgisi', models.BooleanField(default=False)),
                ('alici_kasa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='virman_alici_kasa', to='muhasebe.kasa', verbose_name='Gonderen Kasa')),
                ('gonderen_kasa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='virman_gonderen_kasa', to='muhasebe.kasa', verbose_name='Gonderen Kasa')),
                ('virman_ait_oldugu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Virman Ait Olduğu')),
            ],
        ),
    ]
