# Generated by Django 4.1.2 on 2023-12-13 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('muhasebe', '0006_gelir_bilgisi_silinme_bilgisi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='urunler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urun_adi', models.CharField(blank=True, max_length=400, null=True, verbose_name='Ürün ADı')),
                ('urun_fiyati', models.FloatField(default=0, verbose_name='Ürün Fiyatı')),
                ('silinme_bilgisi', models.BooleanField(default=False)),
                ('virman_ait_oldugu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Virman Ait Olduğu')),
            ],
        ),
    ]
