# Generated by Django 4.1.2 on 2023-12-16 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muhasebe', '0008_remove_gelir_bilgisi_adet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cari',
            name='kayit_tarihi',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='gelir_bilgisi',
            name='kayit_tarihi',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='gelir_etiketi',
            name='kayit_tarihi',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='gelir_kategorisi',
            name='kayit_tarihi',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='gelir_urun_bilgisi',
            name='kayit_tarihi',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='gider_bilgisi',
            name='kayit_tarihi',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='gider_etiketi',
            name='kayit_tarihi',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='gider_kategorisi',
            name='kayit_tarihi',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='gider_urun_bilgisi',
            name='kayit_tarihi',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='kasa',
            name='kayit_tarihi',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='urunler',
            name='kayit_tarihi',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='virman',
            name='kayit_tarihi',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
