# Generated by Django 4.1.2 on 2023-12-19 14:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muhasebe', '0009_cari_kayit_tarihi_gelir_bilgisi_kayit_tarihi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='virman',
            name='veri_tarihi_tarihi',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='virman',
            name='alici_kasa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='virman_alici_kasa', to='muhasebe.kasa', verbose_name='gönderilen Kasa'),
        ),
    ]
