# Generated by Django 4.1.2 on 2023-12-19 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muhasebe', '0010_virman_veri_tarihi_tarihi_alter_virman_alici_kasa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virman',
            name='veri_tarihi_tarihi',
        ),
    ]
