# Generated by Django 4.1.2 on 2023-12-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muhasebe', '0011_remove_virman_veri_tarihi_tarihi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virman',
            name='virman_tarihi',
            field=models.DateField(blank=True, null=True, verbose_name='Virman Tarihi'),
        ),
    ]
