# Generated by Django 4.1.2 on 2023-12-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muhasebe', '0012_alter_virman_virman_tarihi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virman',
            name='virman_tarihi',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Virman Tarihi'),
        ),
    ]
