# Generated by Django 4.1.2 on 2024-01-08 10:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muhasebe', '0014_gelir_bilgisi_odeme_bilgisi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gider_odemesi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutar', models.FloatField(default=0, verbose_name='Tutar')),
                ('silinme_bilgisi', models.BooleanField(default=False)),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('gider_kime_ait_oldugu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='muhasebe.gider_bilgisi', verbose_name='Gelir Ödemesi Kime Ait')),
            ],
        ),
        migrations.CreateModel(
            name='Gelir_odemesi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutar', models.FloatField(default=0, verbose_name='Tutar')),
                ('silinme_bilgisi', models.BooleanField(default=False)),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('gelir_kime_ait_oldugu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='muhasebe.gelir_bilgisi', verbose_name='Gelir Ödemesi Kime Ait')),
            ],
        ),
    ]
