# Generated by Django 4.1.2 on 2024-01-08 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muhasebe', '0015_gider_odemesi_gelir_odemesi'),
    ]

    operations = [
        migrations.AddField(
            model_name='gelir_odemesi',
            name='gelir_makbuzu',
            field=models.FileField(default=0, upload_to='makbuzlar/', verbose_name='Sayfaya Logo Light'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gider_odemesi',
            name='gider_makbuzu',
            field=models.FileField(default=0, upload_to='makbuzlar/', verbose_name='Sayfaya Logo Light'),
            preserve_default=False,
        ),
    ]
