# Generated by Django 4.1.2 on 2024-01-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muhasebe', '0016_gelir_odemesi_gelir_makbuzu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gelir_odemesi',
            name='gelir_makbuzu',
            field=models.FileField(blank=True, null=True, upload_to='makbuzlar/', verbose_name='Sayfaya Logo Light'),
        ),
        migrations.AlterField(
            model_name='gider_odemesi',
            name='gider_makbuzu',
            field=models.FileField(blank=True, null=True, upload_to='makbuzlar/', verbose_name='Sayfaya Logo Light'),
        ),
    ]
