# Generated by Django 4.1.2 on 2024-01-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muhasebe', '0018_faturalar_icin_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gelir_bilgisi',
            name='odeme_bilgisi',
        ),
        migrations.RemoveField(
            model_name='gelir_bilgisi',
            name='tutar',
        ),
        migrations.AddField(
            model_name='gelir_bilgisi',
            name='vade_tarihi',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Vade Tarihi'),
        ),
    ]
