# Generated by Django 4.1.2 on 2024-01-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muhasebe', '0019_remove_gelir_bilgisi_odeme_bilgisi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gelir_urun_bilgisi',
            name='urun_indirimi',
            field=models.FloatField(default=0, verbose_name='Ürün Fiyatı'),
        ),
    ]
