# Generated by Django 4.1.2 on 2024-01-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muhasebe', '0020_gelir_urun_bilgisi_urun_indirimi'),
    ]

    operations = [
        migrations.AddField(
            model_name='gelir_urun_bilgisi',
            name='aciklama',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='gelir_urun_bilgisi',
            name='urun_adeti',
            field=models.BigIntegerField(default=0, verbose_name='Ürün Adeti'),
        ),
    ]
