# Generated by Django 4.1.2 on 2024-02-02 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muhasebe', '0021_gelir_urun_bilgisi_aciklama_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gelir_odemesi',
            name='aciklama',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='gelir_odemesi',
            name='gelir_turu',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='gelir_turu'),
        ),
        migrations.AddField(
            model_name='gelir_odemesi',
            name='kasa_bilgisi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='muhasebe.kasa', verbose_name='Kasa'),
        ),
        migrations.AddField(
            model_name='gelir_odemesi',
            name='makbuz_no',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Makbuz No'),
        ),
        migrations.AddField(
            model_name='gelir_odemesi',
            name='tarihi',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
