# Generated by Django 4.1.2 on 2024-02-09 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muhasebe', '0022_gelir_odemesi_aciklama_gelir_odemesi_gelir_turu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gider_bilgisi',
            name='gider_etiketi_sec',
        ),
        migrations.RemoveField(
            model_name='gider_bilgisi',
            name='gider_kategorisi',
        ),
        migrations.RemoveField(
            model_name='gider_bilgisi',
            name='tutar',
        ),
        migrations.AddField(
            model_name='gider_bilgisi',
            name='gelir_etiketi_sec',
            field=models.ManyToManyField(blank=True, null=True, to='muhasebe.gelir_etiketi'),
        ),
        migrations.AddField(
            model_name='gider_bilgisi',
            name='gelir_kategorisi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='muhasebe.gelir_kategorisi', verbose_name='Gelirin Kategori Bilgisi'),
        ),
        migrations.AddField(
            model_name='gider_bilgisi',
            name='vade_tarihi',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Vade Tarihi'),
        ),
    ]
