# Generated by Django 4.1.2 on 2024-02-09 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('muhasebe', '0023_remove_gider_bilgisi_gider_etiketi_sec_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gider_bilgisi',
            name='gider_kime_ait_oldugu',
        ),
        migrations.AddField(
            model_name='gider_bilgisi',
            name='gelir_kime_ait_oldugu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Gelir Kategorisi Ait Olduğu'),
        ),
        migrations.AlterField(
            model_name='gider_bilgisi',
            name='gelir_etiketi_sec',
            field=models.ManyToManyField(blank=True, null=True, to='muhasebe.gider_etiketi'),
        ),
        migrations.AlterField(
            model_name='gider_bilgisi',
            name='gelir_kategorisi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='muhasebe.gider_kategorisi', verbose_name='Gelirin Kategori Bilgisi'),
        ),
    ]
