# Generated by Django 4.1.2 on 2024-02-10 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muhasebe', '0024_remove_gider_bilgisi_gider_kime_ait_oldugu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gider_urun_bilgisi',
            name='aciklama',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='gider_urun_bilgisi',
            name='urun_indirimi',
            field=models.FloatField(default=0, verbose_name='Ürün Fiyatı'),
        ),
        migrations.AlterField(
            model_name='gider_urun_bilgisi',
            name='gider_bilgis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='muhasebe.gider_bilgisi', verbose_name='Gelir Bilgisi'),
        ),
        migrations.AlterField(
            model_name='gider_urun_bilgisi',
            name='urun_adeti',
            field=models.BigIntegerField(default=0, verbose_name='Ürün Adeti'),
        ),
    ]
