# Generated by Django 4.1.2 on 2024-02-10 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muhasebe', '0025_gider_urun_bilgisi_aciklama_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gider_odemesi',
            old_name='gider_makbuzu',
            new_name='gelir_makbuzu',
        ),
        migrations.RemoveField(
            model_name='gider_odemesi',
            name='gider_kime_ait_oldugu',
        ),
        migrations.AddField(
            model_name='gider_odemesi',
            name='aciklama',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='gider_odemesi',
            name='gelir_kime_ait_oldugu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='muhasebe.gelir_bilgisi', verbose_name='Gelir Ödemesi Kime Ait'),
        ),
        migrations.AddField(
            model_name='gider_odemesi',
            name='gelir_turu',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='gelir_turu'),
        ),
        migrations.AddField(
            model_name='gider_odemesi',
            name='kasa_bilgisi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='muhasebe.kasa', verbose_name='Kasa'),
        ),
        migrations.AddField(
            model_name='gider_odemesi',
            name='makbuz_no',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Makbuz No'),
        ),
        migrations.AddField(
            model_name='gider_odemesi',
            name='tarihi',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
