# Generated by Django 4.1.2 on 2024-02-10 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muhasebe', '0026_rename_gider_makbuzu_gider_odemesi_gelir_makbuzu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gider_odemesi',
            name='gelir_kime_ait_oldugu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='muhasebe.gider_bilgisi', verbose_name='Gelir Ödemesi Kime Ait'),
        ),
    ]
