# Generated by Django 4.1.2 on 2024-02-17 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muhasebe', '0028_gelir_odemesi_islemi_yapan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gelir_bilgisi',
            name='doviz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Döviz'),
        ),
        migrations.AddField(
            model_name='gider_bilgisi',
            name='doviz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Döviz'),
        ),
    ]
