# Generated by Django 4.1.2 on 2024-03-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muhasebe', '0030_gelir_qr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gelir_qr',
            name='qr_bilgisi',
            field=models.ImageField(blank=True, null=True, upload_to='faturaqr/', verbose_name='Sayfaya Logo Light'),
        ),
    ]
