# Generated by Django 4.2.13 on 2024-06-25 00:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('muhasebe', '0034_historicalvirman_historicalurunler_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gider_excel_ekleme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gelir_makbuzu', models.FileField(blank=True, null=True, upload_to='excel/', verbose_name='Sayfaya Logo Light')),
                ('gelir_kime_ait_oldugu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Gelir Ödemesi Kime Ait')),
            ],
        ),
        migrations.CreateModel(
            name='Gelir_excel_ekleme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gelir_makbuzu', models.FileField(blank=True, null=True, upload_to='excel/', verbose_name='Sayfaya Logo Light')),
                ('gelir_kime_ait_oldugu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Gelir Ödemesi Kime Ait')),
            ],
        ),
    ]
