# Generated by Django 4.2.13 on 2024-07-14 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muhasebe', '0035_gider_excel_ekleme_gelir_excel_ekleme'),
    ]

    operations = [
        migrations.AddField(
            model_name='gelir_excel_ekleme',
            name='kasa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='muhasebe.kasa', verbose_name='Kasa'),
        ),
        migrations.AddField(
            model_name='gider_excel_ekleme',
            name='kasa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='muhasebe.kasa', verbose_name='Kasa'),
        ),
    ]
