# Generated by Django 4.2.13 on 2024-08-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muhasebe', '0036_gelir_excel_ekleme_kasa_gider_excel_ekleme_kasa'),
    ]

    operations = [
        migrations.AddField(
            model_name='gelir_bilgisi',
            name='kalan_tutar',
            field=models.FloatField(default=0, verbose_name='Kalan Tutar'),
        ),
        migrations.AddField(
            model_name='gelir_bilgisi',
            name='toplam_tutar',
            field=models.FloatField(default=0, verbose_name='Toplam Tutar'),
        ),
        migrations.AddField(
            model_name='gider_bilgisi',
            name='kalan_tutar',
            field=models.FloatField(default=0, verbose_name='Kalan Tutar'),
        ),
        migrations.AddField(
            model_name='gider_bilgisi',
            name='toplam_tutar',
            field=models.FloatField(default=0, verbose_name='Toplam Tutar'),
        ),
        migrations.AddField(
            model_name='historicalgelir_bilgisi',
            name='kalan_tutar',
            field=models.FloatField(default=0, verbose_name='Kalan Tutar'),
        ),
        migrations.AddField(
            model_name='historicalgelir_bilgisi',
            name='toplam_tutar',
            field=models.FloatField(default=0, verbose_name='Toplam Tutar'),
        ),
        migrations.AddField(
            model_name='historicalgider_bilgisi',
            name='kalan_tutar',
            field=models.FloatField(default=0, verbose_name='Kalan Tutar'),
        ),
        migrations.AddField(
            model_name='historicalgider_bilgisi',
            name='toplam_tutar',
            field=models.FloatField(default=0, verbose_name='Toplam Tutar'),
        ),
    ]
