# Generated by Django 4.2.13 on 2024-08-24 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muhasebe', '0037_gelir_bilgisi_kalan_tutar_gelir_bilgisi_toplam_tutar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gelir_bilgisi',
            old_name='gelir_kategorisi',
            new_name='gelir_kategorisii',
        ),
        migrations.RenameField(
            model_name='historicalgelir_bilgisi',
            old_name='gelir_kategorisi',
            new_name='gelir_kategorisii',
        ),
    ]
