# Generated by Django 4.2.13 on 2024-08-25 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muhasebe', '0039_rename_gelir_kategorisi_gider_bilgisi_gelir_kategorisii_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gelir_bilgisi',
            name='fatura_gorseli',
            field=models.FileField(blank=True, null=True, upload_to='fatura_gorseli/', verbose_name='fatura Görseli'),
        ),
        migrations.AddField(
            model_name='gider_bilgisi',
            name='fatura_gorseli',
            field=models.FileField(blank=True, null=True, upload_to='fatura_gorseli/', verbose_name='fatura Görseli'),
        ),
        migrations.AddField(
            model_name='historicalgelir_bilgisi',
            name='fatura_gorseli',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='fatura Görseli'),
        ),
        migrations.AddField(
            model_name='historicalgider_bilgisi',
            name='fatura_gorseli',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='fatura Görseli'),
        ),
    ]
