# Generated by Django 4.2.13 on 2024-09-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muhasebe', '0041_historicalfaturalar_icin_bilgiler_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalurunler',
            name='stok_mu',
            field=models.BooleanField(default=False, verbose_name='Stok İse Tik Seçilidir'),
        ),
        migrations.AddField(
            model_name='historicalurunler',
            name='urun_turu_secim',
            field=models.CharField(choices=[('1', '1'), ('2', '2')], default='1', max_length=5, verbose_name='Urun Türü'),
        ),
        migrations.AddField(
            model_name='urunler',
            name='stok_mu',
            field=models.BooleanField(default=False, verbose_name='Stok İse Tik Seçilidir'),
        ),
        migrations.AddField(
            model_name='urunler',
            name='urun_turu_secim',
            field=models.CharField(choices=[('1', '1'), ('2', '2')], default='1', max_length=5, verbose_name='Urun Türü'),
        ),
    ]
