# Generated by Django 4.2.13 on 2024-09-07 23:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('muhasebe', '0043_urun_talepleri_historicalurun_talepleri'),
    ]

    operations = [
        migrations.CreateModel(
            name='urun_kategorileri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori_adi', models.CharField(blank=True, max_length=400, null=True, verbose_name='Kategori ADı')),
                ('silinme_bilgisi', models.BooleanField(default=False)),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('kategrori_ait_oldugu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='KAtegori Ait Olduğu')),
            ],
        ),
        migrations.CreateModel(
            name='Historicalurun_kategorileri',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('kategori_adi', models.CharField(blank=True, max_length=400, null=True, verbose_name='Kategori ADı')),
                ('silinme_bilgisi', models.BooleanField(default=False)),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('kategrori_ait_oldugu', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='KAtegori Ait Olduğu')),
            ],
            options={
                'verbose_name': 'historical urun_kategorileri',
                'verbose_name_plural': 'historical urun_kategorileris',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='historicalurunler',
            name='urun_kategorisi',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='muhasebe.urun_kategorileri', verbose_name='ürün Kategorisi'),
        ),
        migrations.AddField(
            model_name='urunler',
            name='urun_kategorisi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='muhasebe.urun_kategorileri', verbose_name='ürün Kategorisi'),
        ),
    ]
