# Generated by Django 4.2.13 on 2024-09-08 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muhasebe', '0044_urun_kategorileri_historicalurun_kategorileri_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalurun_talepleri',
            name='silinme_bilgisi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='urun_talepleri',
            name='silinme_bilgisi',
            field=models.BooleanField(default=False),
        ),
    ]
