# Generated by Django 4.2.13 on 2024-09-09 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('muhasebe', '0046_historicalurun_talepleri_talebi_onaylayan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalurun_talepleri',
            name='satin_almayi_onaylayan',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='SAtın Almayı Onaylayan'),
        ),
        migrations.AddField(
            model_name='urun_talepleri',
            name='satin_almayi_onaylayan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='satin_almayi_onaylayan', to=settings.AUTH_USER_MODEL, verbose_name='SAtın Almayı Onaylayan'),
        ),
        migrations.AlterField(
            model_name='historicalurun_talepleri',
            name='talebi_onaylayan',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Talebi onaylayan'),
        ),
        migrations.AlterField(
            model_name='urun_talepleri',
            name='talebi_onaylayan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talebi_onaylayan', to=settings.AUTH_USER_MODEL, verbose_name='Talebi onaylayan'),
        ),
    ]
