# Generated by Django 4.2.13 on 2024-09-09 21:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0032_historicalpersonel_izinleri_stok_olusturma_and_more'),
        ('muhasebe', '0047_historicalurun_talepleri_satin_almayi_onaylayan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='zimmet_olayi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zimmet_verilis_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Zimmet Veriliş Tarihi')),
                ('zimmet_teslim_edilme_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='zimmet_teslim_edilme_tarihi')),
                ('zimmet_durumu', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2')], default='0', max_length=5, verbose_name='Urun Türü')),
                ('zimet_veris_belgesi', models.FileField(blank=True, null=True, upload_to='zimmet_verilis_belgesi/', verbose_name='Zimmet Belgesi')),
                ('zimet_teslim_belgesi', models.FileField(blank=True, null=True, upload_to='zimmet_teslim_belgesi/', verbose_name='Zimmet Belgesi')),
                ('silinme_bilgisi', models.BooleanField(default=False)),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('zimmet_alan_personel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Zimmet_alan_personel', to='users.calisanlar', verbose_name='Talebin Ait Olduğu')),
                ('zimmet_kime_ait', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zimmet_kime_ait', to=settings.AUTH_USER_MODEL, verbose_name='ürün Ait Olduğu')),
                ('zimmet_verilen_urun', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Zimmet_alan_personel', to='muhasebe.urunler', verbose_name='Talebin Ait Olduğu')),
                ('zimmeti_veren', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zimmeti_veren', to=settings.AUTH_USER_MODEL, verbose_name='Talebin Ait Olduğu')),
            ],
        ),
        migrations.CreateModel(
            name='stok_giris_cikis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stok_giris_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='stok_giris_tarihi')),
                ('stok_adeti', models.FloatField(default=0, verbose_name='Stok Miktari')),
                ('stok_durumu', models.CharField(choices=[('0', '0'), ('1', '1')], default='0', max_length=5, verbose_name='Urun Türü')),
                ('silinme_bilgisi', models.BooleanField(default=False)),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('stok_giren', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stok_giren', to=settings.AUTH_USER_MODEL, verbose_name='Talebin Ait Olduğu')),
                ('stok_giren_urun', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stok_giren_urun', to='muhasebe.urunler', verbose_name='Talebin Ait Olduğu')),
                ('stok_kime_ait', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stok_kime_ait', to=settings.AUTH_USER_MODEL, verbose_name='ürün Ait Olduğu')),
            ],
        ),
        migrations.CreateModel(
            name='Historicalzimmet_olayi',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('zimmet_verilis_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Zimmet Veriliş Tarihi')),
                ('zimmet_teslim_edilme_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='zimmet_teslim_edilme_tarihi')),
                ('zimmet_durumu', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2')], default='0', max_length=5, verbose_name='Urun Türü')),
                ('zimet_veris_belgesi', models.TextField(blank=True, max_length=100, null=True, verbose_name='Zimmet Belgesi')),
                ('zimet_teslim_belgesi', models.TextField(blank=True, max_length=100, null=True, verbose_name='Zimmet Belgesi')),
                ('silinme_bilgisi', models.BooleanField(default=False)),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('zimmet_alan_personel', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.calisanlar', verbose_name='Talebin Ait Olduğu')),
                ('zimmet_kime_ait', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ürün Ait Olduğu')),
                ('zimmet_verilen_urun', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='muhasebe.urunler', verbose_name='Talebin Ait Olduğu')),
                ('zimmeti_veren', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Talebin Ait Olduğu')),
            ],
            options={
                'verbose_name': 'historical zimmet_olayi',
                'verbose_name_plural': 'historical zimmet_olayis',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Historicalstok_giris_cikis',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('stok_giris_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='stok_giris_tarihi')),
                ('stok_adeti', models.FloatField(default=0, verbose_name='Stok Miktari')),
                ('stok_durumu', models.CharField(choices=[('0', '0'), ('1', '1')], default='0', max_length=5, verbose_name='Urun Türü')),
                ('silinme_bilgisi', models.BooleanField(default=False)),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('stok_giren', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Talebin Ait Olduğu')),
                ('stok_giren_urun', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='muhasebe.urunler', verbose_name='Talebin Ait Olduğu')),
                ('stok_kime_ait', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ürün Ait Olduğu')),
            ],
            options={
                'verbose_name': 'historical stok_giris_cikis',
                'verbose_name_plural': 'historical stok_giris_cikiss',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
