# Generated by Django 4.2.13 on 2024-09-09 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muhasebe', '0048_zimmet_olayi_stok_giris_cikis_historicalzimmet_olayi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalzimmet_olayi',
            name='zimmet_miktari',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='zimmet_olayi',
            name='zimmet_miktari',
            field=models.FloatField(default=0),
        ),
    ]
