# Generated by Django 4.2.13 on 2024-09-09 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muhasebe', '0049_historicalzimmet_olayi_zimmet_miktari_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalstok_giris_cikis',
            name='stok_giris_tarihi',
        ),
        migrations.RemoveField(
            model_name='stok_giris_cikis',
            name='stok_giris_tarihi',
        ),
    ]
