# Generated by Django 4.2.13 on 2024-09-14 02:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0035_remove_historicalcalisanlar_calismalari_odemeleri_calisan_and_more'),
        ('muhasebe', '0050_remove_historicalstok_giris_cikis_stok_giris_tarihi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historicalcalisanlar_calismalari_odemeleri',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('tutar', models.FloatField(blank=True, default=0, null=True, verbose_name='Tutar')),
                ('tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Çalışma Tarihi')),
                ('odeme_turu', models.BooleanField(default=False)),
                ('guncelleme_tarihi', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date modified')),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('calisan', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.calisanlar', verbose_name='Çalışan')),
                ('fatura', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='muhasebe.gider_bilgisi', verbose_name='Gider F')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical calisanlar_calismalari_odemeleri',
                'verbose_name_plural': 'historical calisanlar_calismalari_odemeleris',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='calisanlar_calismalari_odemeleri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutar', models.FloatField(blank=True, default=0, null=True, verbose_name='Tutar')),
                ('tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Çalışma Tarihi')),
                ('odeme_turu', models.BooleanField(default=False)),
                ('guncelleme_tarihi', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date modified')),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('calisan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.calisanlar', verbose_name='Çalışan')),
                ('fatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='muhasebe.gider_bilgisi', verbose_name='Gider F')),
            ],
        ),
    ]
