# Generated by Django 4.2.13 on 2024-09-15 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muhasebe', '0051_historicalcalisanlar_calismalari_odemeleri_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calisanlar_calismalari_odemeleri',
            name='aciklama',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='calisanlar_calismalari_odemeleri',
            name='dosya',
            field=models.FileField(blank=True, null=True, upload_to='personel_odeme/', verbose_name='Sayfaya Logo Light'),
        ),
        migrations.AddField(
            model_name='calisanlar_calismalari_odemeleri',
            name='kur',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='kur'),
        ),
        migrations.AddField(
            model_name='calisanlar_calismalari_odemeleri',
            name='odeme_tarihi',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Çdeme Tarihi'),
        ),
        migrations.AddField(
            model_name='historicalcalisanlar_calismalari_odemeleri',
            name='aciklama',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='historicalcalisanlar_calismalari_odemeleri',
            name='dosya',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Sayfaya Logo Light'),
        ),
        migrations.AddField(
            model_name='historicalcalisanlar_calismalari_odemeleri',
            name='kur',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='kur'),
        ),
        migrations.AddField(
            model_name='historicalcalisanlar_calismalari_odemeleri',
            name='odeme_tarihi',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Çdeme Tarihi'),
        ),
        migrations.AlterField(
            model_name='calisanlar_calismalari_odemeleri',
            name='fatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='muhasebe.gider_bilgisi', verbose_name='Gider Faturası'),
        ),
        migrations.AlterField(
            model_name='historicalcalisanlar_calismalari_odemeleri',
            name='fatura',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='muhasebe.gider_bilgisi', verbose_name='Gider Faturası'),
        ),
    ]
