# Generated by Django 4.2.13 on 2024-09-15 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muhasebe', '0052_calisanlar_calismalari_odemeleri_aciklama_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalurunler',
            name='avans_icin_kullan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalurunler',
            name='maas_icin_kullan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='urunler',
            name='avans_icin_kullan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='urunler',
            name='maas_icin_kullan',
            field=models.BooleanField(default=False),
        ),
    ]
