# Generated by Django 4.2.13 on 2024-09-15 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muhasebe', '0053_historicalurunler_avans_icin_kullan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gider_etiketi',
            name='avans_icin_kullan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gider_etiketi',
            name='maas_icin_kullan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gider_kategorisi',
            name='avans_icin_kullan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gider_kategorisi',
            name='maas_icin_kullan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalgider_etiketi',
            name='avans_icin_kullan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalgider_etiketi',
            name='maas_icin_kullan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalgider_kategorisi',
            name='avans_icin_kullan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalgider_kategorisi',
            name='maas_icin_kullan',
            field=models.BooleanField(default=False),
        ),
    ]
