# Generated by Django 4.2.13 on 2024-09-15 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muhasebe', '0054_gider_etiketi_avans_icin_kullan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalkasa',
            name='avans_icin_kullan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalkasa',
            name='maas_icin_kullan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kasa',
            name='avans_icin_kullan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kasa',
            name='maas_icin_kullan',
            field=models.BooleanField(default=False),
        ),
    ]
