# Generated by Django 4.2.13 on 2024-11-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muhasebe', '0055_historicalkasa_avans_icin_kullan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faturalar_icin_bilgiler',
            name='gunluk_calisma_saati',
            field=models.FloatField(default=9, verbose_name='Günlük Çalışma Saati'),
        ),
        migrations.AddField(
            model_name='historicalfaturalar_icin_bilgiler',
            name='gunluk_calisma_saati',
            field=models.FloatField(default=9, verbose_name='Günlük Çalışma Saati'),
        ),
    ]
