from django.contrib import admin

# Register your models here.
from .models import * 
admin.site.register(sayfa_logosu)
admin.site.register(sayfa_iconu)
admin.site.register(site_adi)
admin.site.register(numara)
admin.site.register(adres)
admin.site.register(gomulu_adres)
admin.site.register(email_adres)
admin.site.register(sosyalmedyaInsgr)
admin.site.register(sosyalmedyalinkd)
admin.site.register(sosyalmedyaFace)
admin.site.register(sosyalmedyayoutube)
admin.site.register(sosyalmedyatw)
admin.site.register(seo_ayarlari)
admin.site.register(banner)
admin.site.register(dil_ayarla)
admin.site.register(faturalardaki_gelir_gider_etiketi)
admin.site.register(layout)
admin.site.register(color_sheme)
admin.site.register(side_bar_gorunum)
admin.site.register(layout_pozisyonu)
admin.site.register(topbar_color)
admin.site.register(sidebar_boyutu)
admin.site.register(sidebar_rengi)
admin.site.register(layout_uzunlugu)
admin.site.register(layout_sitili)
admin.site.register(ApiKey)

