# Generated by Django 3.2.18 on 2023-12-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dil_ayarla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dil_adi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dil Adı')),
                ('dil_kisaltması', models.CharField(blank=True, max_length=5, null=True, verbose_name='Dİl Kısaltması')),
                ('dil_bayragi_icon', models.FileField(upload_to='bayrak/', verbose_name='Dil Bayrağı')),
            ],
        ),
    ]
