# Generated by Django 3.2.18 on 2023-12-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_dil_ayarla'),
    ]

    operations = [
        migrations.AddField(
            model_name='dil_ayarla',
            name='dil_aktiflik_durumu',
            field=models.BooleanField(default=False, verbose_name='Dİl Aktiflik Durumu'),
        ),
    ]
