# Generated by Django 4.1.2 on 2024-01-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_dil_ayarla_dil_aktiflik_durumu'),
    ]

    operations = [
        migrations.AddField(
            model_name='site_adi',
            name='footer',
            field=models.CharField(default=0, max_length=200, verbose_name='Footer'),
            preserve_default=False,
        ),
    ]
