# Generated by Django 4.1.2 on 2024-01-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0004_site_adi_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='sayfa_logosu',
            name='l_image',
            field=models.ImageField(default=0, upload_to='logo/', verbose_name='Sayfaya Logo Light'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sayfa_logosu',
            name='image',
            field=models.ImageField(upload_to='logo/', verbose_name='Sayfaya Logo Dark'),
        ),
    ]
