# Generated by Django 4.1.2 on 2024-01-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0005_sayfa_logosu_l_image_alter_sayfa_logosu_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='faturalardaki_gelir_gider_etiketi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gelir_etiketi', models.CharField(blank=True, max_length=10, null=True, verbose_name='Gelir Etiketi')),
                ('gider_etiketi', models.CharField(blank=True, max_length=10, null=True, verbose_name='Gider Etiketi')),
            ],
        ),
    ]
