# Generated by Django 4.1.2 on 2024-01-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0007_color_sheme_layout_layout_pozisyonu_side_bar_gorunum_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='layout_uzunlugu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=500, verbose_name='Görünüş isimleri')),
                ('data_layout_width', models.CharField(max_length=500, verbose_name='Görünüş Anahtarı')),
                ('aktiflik', models.BooleanField(default=False)),
            ],
        ),
    ]
