# Generated by Django 4.1.2 on 2024-01-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0009_layout_sitili'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sayfa_logosu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='Sayfaya Logo Dark'),
        ),
        migrations.AlterField(
            model_name='sayfa_logosu',
            name='l_image',
            field=models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='Sayfaya Logo Light'),
        ),
    ]
