# Generated by Django 4.1.2 on 2024-01-15 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0010_alter_sayfa_logosu_image_alter_sayfa_logosu_l_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sayfa_logosu',
            old_name='l_image',
            new_name='dark_image',
        ),
    ]
