# Generated by Django 4.1.2 on 2024-06-23 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0011_rename_l_image_sayfa_logosu_dark_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='loglar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
