# Generated by Django 4.1.2 on 2024-06-23 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0012_loglar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='loglar',
            new_name='MyModel',
        ),
    ]
