# Generated by Django 4.1.2 on 2024-06-23 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0013_rename_loglar_mymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='json_data',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
