# Generated by Django 4.1.2 on 2024-06-23 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0014_mymodel_json_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
