# Generated by Django 4.2.13 on 2025-04-11 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('site_settings', '0017_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='faturalardaki_gelir_gider_etiketi',
            name='kime_ait',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Proje Ait Olduğu'),
        ),
        migrations.AddField(
            model_name='historicalfaturalardaki_gelir_gider_etiketi',
            name='kime_ait',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Proje Ait Olduğu'),
        ),
    ]
